// ============================================================
// 词库扩展（第二部分）：新增 16 个主题，使词汇总量达到 800
// 由 data.js 加载后执行：把新主题插入到 phrases 之前，保持词汇主题集中
// 每个词条内联 phonetic 字段，buildQuestionPool 会优先读取
// ============================================================
(function () {
  const newThemes = [
  {
    id: 'family', level: 'starter', name: '👨‍👩‍👧 我的家人', icon: '👨‍👩‍👧',
    items: [
      { en: 'Father', phonetic: '/ˈfɑːðər/', zh: '爸爸', emoji: '👨', sentence: 'This is my father.', sentenceZh: '这是我爸爸。' },
      { en: 'Mother', phonetic: '/ˈmʌðər/', zh: '妈妈', emoji: '👩', sentence: 'This is my mother.', sentenceZh: '这是我妈妈。' },
      { en: 'Brother', phonetic: '/ˈbrʌðər/', zh: '兄弟', emoji: '👦', sentence: 'My brother is tall.', sentenceZh: '我的兄弟很高。' },
      { en: 'Sister', phonetic: '/ˈsɪstər/', zh: '姐妹', emoji: '👧', sentence: 'My sister is cute.', sentenceZh: '我的姐妹很可爱。' },
      { en: 'Grandpa', phonetic: '/ˈɡrænpɑː/', zh: '爷爷', emoji: '👴', sentence: 'Grandpa tells stories.', sentenceZh: '爷爷讲故事。' },
      { en: 'Grandma', phonetic: '/ˈɡrænmɑː/', zh: '奶奶', emoji: '👵', sentence: 'Grandma bakes cookies.', sentenceZh: '奶奶烤饼干。' },
      { en: 'Uncle', phonetic: '/ˈʌŋkl/', zh: '叔叔', emoji: '🧔', sentence: 'My uncle is funny.', sentenceZh: '我叔叔很有趣。' },
      { en: 'Aunt', phonetic: '/ɑːnt/', zh: '阿姨', emoji: '👩', sentence: 'Aunt gives me a gift.', sentenceZh: '阿姨给我礼物。' },
      { en: 'Cousin', phonetic: '/ˈkʌzn/', zh: '表亲', emoji: '🧒', sentence: 'My cousin comes to play.', sentenceZh: '我的表哥来玩。' },
      { en: 'Son', phonetic: '/sʌn/', zh: '儿子', emoji: '👦', sentence: 'He is their son.', sentenceZh: '他是他们的儿子。' },
      { en: 'Daughter', phonetic: '/ˈdɔːtər/', zh: '女儿', emoji: '👧', sentence: 'She is their daughter.', sentenceZh: '她是他们的女儿。' },
      { en: 'Baby', phonetic: '/ˈbeɪbi/', zh: '宝宝', emoji: '👶', sentence: 'The baby is sleeping.', sentenceZh: '宝宝在睡觉。' },
      { en: 'Family', phonetic: '/ˈfæməli/', zh: '家庭', emoji: '👨‍👩‍👧‍👦', sentence: 'I love my family.', sentenceZh: '我爱我的家。' },
      { en: 'Kid', phonetic: '/kɪd/', zh: '小孩', emoji: '🧒', sentence: 'The kid is happy.', sentenceZh: '那个小孩很开心。' },
      { en: 'Boy', phonetic: '/bɔɪ/', zh: '男孩', emoji: '👦', sentence: 'The boy runs fast.', sentenceZh: '男孩跑得快。' },
      { en: 'Girl', phonetic: '/ɡɜːl/', zh: '女孩', emoji: '👧', sentence: 'The girl sings well.', sentenceZh: '女孩唱歌好听。' },
      { en: 'Man', phonetic: '/mæn/', zh: '男人', emoji: '👨', sentence: 'The man is strong.', sentenceZh: '那个男人很强壮。' },
      { en: 'Woman', phonetic: '/ˈwʊmən/', zh: '女人', emoji: '👩', sentence: 'The woman is kind.', sentenceZh: '那个女人很善良。' },
      { en: 'Friend', phonetic: '/frend/', zh: '朋友', emoji: '🤝', sentence: 'He is my friend.', sentenceZh: '他是我的朋友。' },
      { en: 'Twin', phonetic: '/twɪn/', zh: '双胞胎', emoji: '👯', sentence: 'They are twins.', sentenceZh: '他们是双胞胎。' },
      { en: 'Neighbor', phonetic: '/ˈneɪbər/', zh: '邻居', emoji: '🏘️', sentence: 'My neighbor is nice.', sentenceZh: '我的邻居很好。' },
      { en: 'Child', phonetic: '/tʃaɪld/', zh: '孩子', emoji: '🧒', sentence: 'The child is playing.', sentenceZh: '孩子在玩。' },
      { en: 'Children', phonetic: '/ˈtʃɪldrən/', zh: '孩子们', emoji: '👧👦', sentence: 'The children are laughing.', sentenceZh: '孩子们在笑。' },
      { en: 'Guest', phonetic: '/ɡest/', zh: '客人', emoji: '🚪', sentence: 'We have a guest today.', sentenceZh: '今天我们有客人。' }
    ]
  },
  {
    id: 'school', level: 'primary', name: '🎒 学校用品', icon: '🎒',
    items: [
      { en: 'Pen', phonetic: '/pen/', zh: '钢笔', emoji: '🖊️', sentence: 'I write with a pen.', sentenceZh: '我用钢笔写字。' },
      { en: 'Pencil', phonetic: '/ˈpensl/', zh: '铅笔', emoji: '✏️', sentence: 'The pencil is yellow.', sentenceZh: '铅笔是黄色的。' },
      { en: 'Eraser', phonetic: '/ɪˈreɪzər/', zh: '橡皮', emoji: '🧽', sentence: 'I use an eraser.', sentenceZh: '我用橡皮。' },
      { en: 'Ruler', phonetic: '/ˈruːlər/', zh: '尺子', emoji: '📏', sentence: 'The ruler is long.', sentenceZh: '尺子很长。' },
      { en: 'Crayon', phonetic: '/ˈkreɪən/', zh: '蜡笔', emoji: '🖍️', sentence: 'I draw with crayons.', sentenceZh: '我用蜡笔画画。' },
      { en: 'Scissors', phonetic: '/ˈsɪzərz/', zh: '剪刀', emoji: '✂️', sentence: 'I cut paper with scissors.', sentenceZh: '我用剪刀剪纸。' },
      { en: 'Glue', phonetic: '/ɡluː/', zh: '胶水', emoji: '🧴', sentence: 'I use glue to stick.', sentenceZh: '我用胶水粘。' },
      { en: 'Paper', phonetic: '/ˈpeɪpər/', zh: '纸', emoji: '📄', sentence: 'The paper is white.', sentenceZh: '纸是白色的。' },
      { en: 'Notebook', phonetic: '/ˈnəʊtbʊk/', zh: '笔记本', emoji: '📓', sentence: 'I write in my notebook.', sentenceZh: '我在笔记本上写字。' },
      { en: 'School bag', phonetic: '/skuːl bæɡ/', zh: '书包', emoji: '🎒', sentence: 'My school bag is heavy.', sentenceZh: '我的书包很重。' },
      { en: 'Desk', phonetic: '/desk/', zh: '课桌', emoji: '🪑', sentence: 'My desk is clean.', sentenceZh: '我的课桌很干净。' },
      { en: 'Blackboard', phonetic: '/ˈblækbɔːd/', zh: '黑板', emoji: '🟫', sentence: 'The teacher writes on the blackboard.', sentenceZh: '老师在黑板上写字。' },
      { en: 'Chalk', phonetic: '/tʃɔːk/', zh: '粉笔', emoji: '🖍️', sentence: 'The chalk is white.', sentenceZh: '粉笔是白色的。' },
      { en: 'Marker', phonetic: '/ˈmɑːkər/', zh: '记号笔', emoji: '🖊️', sentence: 'The marker is red.', sentenceZh: '记号笔是红色的。' },
      { en: 'Stapler', phonetic: '/ˈsteɪplər/', zh: '订书机', emoji: '🗂️', sentence: 'I use a stapler.', sentenceZh: '我用订书机。' },
      { en: 'Sharpener', phonetic: '/ˈʃɑːpənər/', zh: '卷笔刀', emoji: '✏️', sentence: 'I use a sharpener.', sentenceZh: '我用卷笔刀。' },
      { en: 'Compass', phonetic: '/ˈkʌmpəs/', zh: '圆规', emoji: '🧭', sentence: 'I draw a circle with a compass.', sentenceZh: '我用圆规画圆。' },
      { en: 'Calculator', phonetic: '/ˈkælkjuleɪtər/', zh: '计算器', emoji: '🧮', sentence: 'The calculator is helpful.', sentenceZh: '计算器很有用。' },
      { en: 'Globe', phonetic: '/ɡləʊb/', zh: '地球仪', emoji: '🌍', sentence: 'The globe is round.', sentenceZh: '地球仪是圆的。' },
      { en: 'Map', phonetic: '/mæp/', zh: '地图', emoji: '🗺️', sentence: 'I read a map.', sentenceZh: '我看地图。' },
      { en: 'Textbook', phonetic: '/ˈtekstbʊk/', zh: '课本', emoji: '📚', sentence: 'Open your textbook.', sentenceZh: '打开你的课本。' },
      { en: 'Dictionary', phonetic: '/ˈdɪkʃənri/', zh: '字典', emoji: '📖', sentence: 'I look up words in a dictionary.', sentenceZh: '我用字典查单词。' },
      { en: 'Pencil case', phonetic: '/ˈpensl keɪs/', zh: '文具盒', emoji: '🧰', sentence: 'My pencil case is blue.', sentenceZh: '我的文具盒是蓝色的。' },
      { en: 'Folder', phonetic: '/ˈfəʊldər/', zh: '文件夹', emoji: '📁', sentence: 'The folder is green.', sentenceZh: '文件夹是绿色的。' },
      { en: 'Sticker', phonetic: '/ˈstɪkər/', zh: '贴纸', emoji: '⭐', sentence: 'I get a sticker.', sentenceZh: '我得到一张贴纸。' },
      { en: 'Homework', phonetic: '/ˈhəʊmwɜːk/', zh: '作业', emoji: '📝', sentence: 'I do my homework.', sentenceZh: '我做作业。' },
      { en: 'Paint', phonetic: '/peɪnt/', zh: '颜料', emoji: '🎨', sentence: 'I paint with colors.', sentenceZh: '我用颜料画画。' },
      { en: 'Clipboard', phonetic: '/ˈklɪpbɔːd/', zh: '板夹', emoji: '📋', sentence: 'He holds a clipboard.', sentenceZh: '他拿着板夹。' }
    ]
  },
  {
    id: 'nature', level: 'primary', name: '🌳 自然万物', icon: '🌳',
    items: [
      { en: 'Tree', phonetic: '/triː/', zh: '树', emoji: '🌳', sentence: 'The tree is tall.', sentenceZh: '树很高。' },
      { en: 'Flower', phonetic: '/ˈflaʊər/', zh: '花', emoji: '🌸', sentence: 'The flower is pretty.', sentenceZh: '花很漂亮。' },
      { en: 'Grass', phonetic: '/ɡrɑːs/', zh: '草', emoji: '🌱', sentence: 'The grass is green.', sentenceZh: '草是绿色的。' },
      { en: 'Mountain', phonetic: '/ˈmaʊntən/', zh: '山', emoji: '⛰️', sentence: 'The mountain is high.', sentenceZh: '山很高。' },
      { en: 'River', phonetic: '/ˈrɪvər/', zh: '河', emoji: '🏞️', sentence: 'The river is long.', sentenceZh: '河很长。' },
      { en: 'Forest', phonetic: '/ˈfɒrɪst/', zh: '森林', emoji: '🌲', sentence: 'The forest is big.', sentenceZh: '森林很大。' },
      { en: 'Rock', phonetic: '/rɒk/', zh: '岩石', emoji: '🪨', sentence: 'The rock is hard.', sentenceZh: '岩石很硬。' },
      { en: 'Leaf', phonetic: '/liːf/', zh: '叶子', emoji: '🍃', sentence: 'The leaf is green.', sentenceZh: '叶子是绿色的。' },
      { en: 'Seed', phonetic: '/siːd/', zh: '种子', emoji: '🌰', sentence: 'I plant a seed.', sentenceZh: '我种下一粒种子。' },
      { en: 'Soil', phonetic: '/sɔɪl/', zh: '泥土', emoji: '🟫', sentence: 'The soil is dark.', sentenceZh: '泥土是深色的。' },
      { en: 'Sand', phonetic: '/sænd/', zh: '沙子', emoji: '🟡', sentence: 'The sand is soft.', sentenceZh: '沙子很软。' },
      { en: 'Hill', phonetic: '/hɪl/', zh: '小山', emoji: '⛰️', sentence: 'I climb the hill.', sentenceZh: '我爬小山。' },
      { en: 'Valley', phonetic: '/ˈvæli/', zh: '山谷', emoji: '🏞️', sentence: 'The valley is green.', sentenceZh: '山谷是绿色的。' },
      { en: 'Island', phonetic: '/ˈaɪlənd/', zh: '岛屿', emoji: '🏝️', sentence: 'The island is small.', sentenceZh: '岛屿很小。' },
      { en: 'Lake', phonetic: '/leɪk/', zh: '湖', emoji: '🏞️', sentence: 'The lake is calm.', sentenceZh: '湖面很平静。' },
      { en: 'Ocean', phonetic: '/ˈəʊʃn/', zh: '海洋', emoji: '🌊', sentence: 'The ocean is deep.', sentenceZh: '海洋很深。' },
      { en: 'Waterfall', phonetic: '/ˈwɔːtəfɔːl/', zh: '瀑布', emoji: '💦', sentence: 'The waterfall is loud.', sentenceZh: '瀑布声音很大。' },
      { en: 'Cave', phonetic: '/keɪv/', zh: '洞穴', emoji: '🕳️', sentence: 'The cave is dark.', sentenceZh: '洞穴很黑。' },
      { en: 'Desert', phonetic: '/ˈdezət/', zh: '沙漠', emoji: '🏜️', sentence: 'The desert is hot.', sentenceZh: '沙漠很热。' },
      { en: 'Field', phonetic: '/fiːld/', zh: '田野', emoji: '🌾', sentence: 'The field is wide.', sentenceZh: '田野很宽。' },
      { en: 'Bush', phonetic: '/bʊʃ/', zh: '灌木', emoji: '🌿', sentence: 'The bush is thick.', sentenceZh: '灌木很密。' },
      { en: 'Branch', phonetic: '/brɑːntʃ/', zh: '树枝', emoji: '🪵', sentence: 'The branch is long.', sentenceZh: '树枝很长。' },
      { en: 'Root', phonetic: '/ruːt/', zh: '根', emoji: '🌱', sentence: 'The root is under the ground.', sentenceZh: '根在地下。' },
      { en: 'Petal', phonetic: '/ˈpetl/', zh: '花瓣', emoji: '🌸', sentence: 'The petal is soft.', sentenceZh: '花瓣很软。' },
      { en: 'Stem', phonetic: '/stem/', zh: '茎', emoji: '🌿', sentence: 'The stem is green.', sentenceZh: '茎是绿色的。' },
      { en: 'Pine', phonetic: '/paɪn/', zh: '松树', emoji: '🌲', sentence: 'The pine is tall.', sentenceZh: '松树很高。' },
      { en: 'Bamboo', phonetic: '/bæmˈbuː/', zh: '竹子', emoji: '🎋', sentence: 'Pandas eat bamboo.', sentenceZh: '熊猫吃竹子。' },
      { en: 'Cactus', phonetic: '/ˈkæktəs/', zh: '仙人掌', emoji: '🌵', sentence: 'The cactus is spiky.', sentenceZh: '仙人掌有刺。' },
      { en: 'Sunflower', phonetic: '/ˈsʌnflaʊər/', zh: '向日葵', emoji: '🌻', sentence: 'The sunflower is yellow.', sentenceZh: '向日葵是黄色的。' },
      { en: 'Rose', phonetic: '/rəʊz/', zh: '玫瑰', emoji: '🌹', sentence: 'The rose is red.', sentenceZh: '玫瑰是红色的。' },
      { en: 'Tulip', phonetic: '/ˈtjuːlɪp/', zh: '郁金香', emoji: '🌷', sentence: 'The tulip is pretty.', sentenceZh: '郁金香很漂亮。' },
      { en: 'Daisy', phonetic: '/ˈdeɪzi/', zh: '雏菊', emoji: '🌼', sentence: 'The daisy is white.', sentenceZh: '雏菊是白色的。' },
      { en: 'Lily', phonetic: '/ˈlɪli/', zh: '百合', emoji: '💮', sentence: 'The lily is white.', sentenceZh: '百合是白色的。' },
      { en: 'Palm', phonetic: '/pɑːm/', zh: '棕榈树', emoji: '🌴', sentence: 'The palm is tall.', sentenceZh: '棕榈树很高。' },
      { en: 'Vine', phonetic: '/vaɪn/', zh: '藤蔓', emoji: '🌿', sentence: 'The vine grows up.', sentenceZh: '藤蔓向上长。' },
      { en: 'Moss', phonetic: '/mɒs/', zh: '苔藓', emoji: '🟩', sentence: 'The moss is soft.', sentenceZh: '苔藓很软。' }
    ]
  },
  {
    id: 'sports', level: 'primary', name: '⚽ 运动游戏', icon: '⚽',
    items: [
      { en: 'Football', phonetic: '/ˈfʊtbɔːl/', zh: '足球', emoji: '⚽', sentence: 'I play football.', sentenceZh: '我踢足球。' },
      { en: 'Basketball', phonetic: '/ˈbɑːskɪtbɔːl/', zh: '篮球', emoji: '🏀', sentence: 'I like basketball.', sentenceZh: '我喜欢篮球。' },
      { en: 'Tennis', phonetic: '/ˈtenɪs/', zh: '网球', emoji: '🎾', sentence: 'Tennis is fun.', sentenceZh: '网球很有趣。' },
      { en: 'Ping-pong', phonetic: '/ˈpɪŋ pɒŋ/', zh: '乒乓球', emoji: '🏓', sentence: 'I play ping-pong.', sentenceZh: '我打乒乓球。' },
      { en: 'Badminton', phonetic: '/ˈbædmɪntən/', zh: '羽毛球', emoji: '🏸', sentence: 'Badminton is easy.', sentenceZh: '羽毛球很容易。' },
      { en: 'Baseball', phonetic: '/ˈbeɪsbɔːl/', zh: '棒球', emoji: '⚾', sentence: 'Baseball is popular.', sentenceZh: '棒球很受欢迎。' },
      { en: 'Volleyball', phonetic: '/ˈvɒlibɔːl/', zh: '排球', emoji: '🏐', sentence: 'We play volleyball.', sentenceZh: '我们打排球。' },
      { en: 'Swimming', phonetic: '/ˈswɪmɪŋ/', zh: '游泳', emoji: '🏊', sentence: 'Swimming is cool.', sentenceZh: '游泳很凉爽。' },
      { en: 'Running', phonetic: '/ˈrʌnɪŋ/', zh: '跑步', emoji: '🏃', sentence: 'Running is good.', sentenceZh: '跑步很好。' },
      { en: 'Cycling', phonetic: '/ˈsaɪklɪŋ/', zh: '骑自行车', emoji: '🚴', sentence: 'I like cycling.', sentenceZh: '我喜欢骑车。' },
      { en: 'Skating', phonetic: '/ˈskeɪtɪŋ/', zh: '滑冰', emoji: '⛸️', sentence: 'Skating is fun.', sentenceZh: '滑冰很有趣。' },
      { en: 'Skiing', phonetic: '/ˈskiːɪŋ/', zh: '滑雪', emoji: '🎿', sentence: 'Skiing is fast.', sentenceZh: '滑雪很快。' },
      { en: 'Jumping', phonetic: '/ˈdʒʌmpɪŋ/', zh: '跳跃', emoji: '🤸', sentence: 'Jumping is fun.', sentenceZh: '跳跃很有趣。' },
      { en: 'Climbing', phonetic: '/ˈklaɪmɪŋ/', zh: '攀爬', emoji: '🧗', sentence: 'Climbing is hard.', sentenceZh: '攀爬很难。' },
      { en: 'Dancing', phonetic: '/ˈdɑːnsɪŋ/', zh: '跳舞', emoji: '💃', sentence: 'Dancing is happy.', sentenceZh: '跳舞很快乐。' },
      { en: 'Yoga', phonetic: '/ˈjəʊɡə/', zh: '瑜伽', emoji: '🧘', sentence: 'Yoga is calm.', sentenceZh: '瑜伽很安静。' },
      { en: 'Boxing', phonetic: '/ˈbɒksɪŋ/', zh: '拳击', emoji: '🥊', sentence: 'Boxing is strong.', sentenceZh: '拳击很有力。' },
      { en: 'Archery', phonetic: '/ˈɑːtʃəri/', zh: '射箭', emoji: '🏹', sentence: 'Archery is cool.', sentenceZh: '射箭很酷。' },
      { en: 'Golf', phonetic: '/ɡɒlf/', zh: '高尔夫', emoji: '⛳', sentence: 'Golf is slow.', sentenceZh: '高尔夫很慢。' },
      { en: 'Bowling', phonetic: '/ˈbəʊlɪŋ/', zh: '保龄球', emoji: '🎳', sentence: 'Bowling is fun.', sentenceZh: '保龄球很有趣。' },
      { en: 'Surfing', phonetic: '/ˈsɜːfɪŋ/', zh: '冲浪', emoji: '🏄', sentence: 'Surfing is cool.', sentenceZh: '冲浪很酷。' },
      { en: 'Diving', phonetic: '/ˈdaɪvɪŋ/', zh: '潜水', emoji: '🤿', sentence: 'Diving is deep.', sentenceZh: '潜水很深。' },
      { en: 'Rowing', phonetic: '/ˈrəʊɪŋ/', zh: '划船', emoji: '🚣', sentence: 'Rowing is fun.', sentenceZh: '划船很有趣。' },
      { en: 'Goal', phonetic: '/ɡəʊl/', zh: '球门', emoji: '🥅', sentence: 'I kick it in the goal.', sentenceZh: '我踢进球门。' }
    ]
  },
  {
    id: 'insects', level: 'starter', name: '🐛 昆虫世界', icon: '🐛',
    items: [
      { en: 'Ant', phonetic: '/ænt/', zh: '蚂蚁', emoji: '🐜', sentence: 'The ant is small.', sentenceZh: '蚂蚁很小。' },
      { en: 'Bee', phonetic: '/biː/', zh: '蜜蜂', emoji: '🐝', sentence: 'The bee makes honey.', sentenceZh: '蜜蜂酿蜜。' },
      { en: 'Butterfly', phonetic: '/ˈbʌtəflaɪ/', zh: '蝴蝶', emoji: '🦋', sentence: 'The butterfly is pretty.', sentenceZh: '蝴蝶很漂亮。' },
      { en: 'Ladybug', phonetic: '/ˈleɪdibʌɡ/', zh: '瓢虫', emoji: '🐞', sentence: 'The ladybug is red.', sentenceZh: '瓢虫是红色的。' },
      { en: 'Grasshopper', phonetic: '/ˈɡrɑːshɒpər/', zh: '蚱蜢', emoji: '🦗', sentence: 'The grasshopper jumps.', sentenceZh: '蚱蜢会跳。' },
      { en: 'Cricket', phonetic: '/ˈkrɪkɪt/', zh: '蟋蟀', emoji: '🦗', sentence: 'The cricket sings.', sentenceZh: '蟋蟀会唱歌。' },
      { en: 'Dragonfly', phonetic: '/ˈdræɡənflaɪ/', zh: '蜻蜓', emoji: '🦋', sentence: 'The dragonfly flies fast.', sentenceZh: '蜻蜓飞得快。' },
      { en: 'Fly', phonetic: '/flaɪ/', zh: '苍蝇', emoji: '🪰', sentence: 'The fly is annoying.', sentenceZh: '苍蝇很烦人。' },
      { en: 'Mosquito', phonetic: '/məˈskiːtəʊ/', zh: '蚊子', emoji: '🦟', sentence: 'The mosquito bites.', sentenceZh: '蚊子会咬人。' },
      { en: 'Spider', phonetic: '/ˈspaɪdər/', zh: '蜘蛛', emoji: '🕷️', sentence: 'The spider makes a web.', sentenceZh: '蜘蛛会织网。' },
      { en: 'Worm', phonetic: '/wɜːm/', zh: '虫子', emoji: '🪱', sentence: 'The worm is soft.', sentenceZh: '虫子很软。' },
      { en: 'Caterpillar', phonetic: '/ˈkætəpɪlər/', zh: '毛毛虫', emoji: '🐛', sentence: 'The caterpillar crawls.', sentenceZh: '毛毛虫会爬。' },
      { en: 'Snail', phonetic: '/sneɪl/', zh: '蜗牛', emoji: '🐌', sentence: 'The snail is slow.', sentenceZh: '蜗牛很慢。' },
      { en: 'Beetle', phonetic: '/ˈbiːtl/', zh: '甲虫', emoji: '🪲', sentence: 'The beetle is shiny.', sentenceZh: '甲虫闪闪发亮。' },
      { en: 'Moth', phonetic: '/mɒθ/', zh: '飞蛾', emoji: '🦋', sentence: 'The moth flies at night.', sentenceZh: '飞蛾晚上飞。' },
      { en: 'Firefly', phonetic: '/ˈfaɪəflaɪ/', zh: '萤火虫', emoji: '✨', sentence: 'The firefly glows.', sentenceZh: '萤火虫会发光。' },
      { en: 'Locust', phonetic: '/ˈləʊkəst/', zh: '蝗虫', emoji: '🦗', sentence: 'The locust hops.', sentenceZh: '蝗虫会跳。' },
      { en: 'Cicada', phonetic: '/sɪˈkɑːdə/', zh: '知了', emoji: '🔊', sentence: 'The cicada is loud.', sentenceZh: '知了很吵。' },
      { en: 'Hornet', phonetic: '/ˈhɔːnɪt/', zh: '黄蜂', emoji: '🐝', sentence: 'The hornet can sting.', sentenceZh: '黄蜂会蜇人。' },
      { en: 'Termite', phonetic: '/ˈtɜːmaɪt/', zh: '白蚁', emoji: '🐜', sentence: 'The termite eats wood.', sentenceZh: '白蚁吃木头。' },
      { en: 'Centipede', phonetic: '/ˈsentɪpiːd/', zh: '蜈蚣', emoji: '🐛', sentence: 'The centipede has many legs.', sentenceZh: '蜈蚣有很多腿。' },
      { en: 'Stag beetle', phonetic: '/stæɡ ˈbiːtl/', zh: '锹形虫', emoji: '🪲', sentence: 'The stag beetle has big jaws.', sentenceZh: '锹形虫有大颚。' }
    ]
  },
  {
    id: 'sea', level: 'starter', name: '🦀 海洋动物', icon: '🦀',
    items: [
      { en: 'Octopus', phonetic: '/ˈɒktəpəs/', zh: '章鱼', emoji: '🐙', sentence: 'The octopus has eight arms.', sentenceZh: '章鱼有八条腕。' },
      { en: 'Squid', phonetic: '/skwɪd/', zh: '鱿鱼', emoji: '🦑', sentence: 'The squid swims fast.', sentenceZh: '鱿鱼游得快。' },
      { en: 'Jellyfish', phonetic: '/ˈdʒelifɪʃ/', zh: '水母', emoji: '🪼', sentence: 'The jellyfish is soft.', sentenceZh: '水母很软。' },
      { en: 'Seahorse', phonetic: '/ˈsiːhɔːs/', zh: '海马', emoji: '🐠', sentence: 'The seahorse is tiny.', sentenceZh: '海马很小。' },
      { en: 'Starfish', phonetic: '/ˈstɑːfɪʃ/', zh: '海星', emoji: '⭐', sentence: 'The starfish has five arms.', sentenceZh: '海星有五个腕。' },
      { en: 'Crab', phonetic: '/kræb/', zh: '螃蟹', emoji: '🦀', sentence: 'The crab walks sideways.', sentenceZh: '螃蟹横着走。' },
      { en: 'Lobster', phonetic: '/ˈlɒbstər/', zh: '龙虾', emoji: '🦞', sentence: 'The lobster has big claws.', sentenceZh: '龙虾有大钳子。' },
      { en: 'Shrimp', phonetic: '/ʃrɪmp/', zh: '虾', emoji: '🦐', sentence: 'The shrimp is small.', sentenceZh: '虾很小。' },
      { en: 'Clam', phonetic: '/klæm/', zh: '蛤蜊', emoji: '🐚', sentence: 'The clam has a hard shell.', sentenceZh: '蛤蜊有硬壳。' },
      { en: 'Oyster', phonetic: '/ˈɔɪstər/', zh: '牡蛎', emoji: '🦪', sentence: 'The oyster makes pearls.', sentenceZh: '牡蛎产珍珠。' },
      { en: 'Sea urchin', phonetic: '/siː ˈɜːtʃɪn/', zh: '海胆', emoji: '🦔', sentence: 'The sea urchin is spiky.', sentenceZh: '海胆有刺。' },
      { en: 'Stingray', phonetic: '/ˈstɪŋreɪ/', zh: '黄貂鱼', emoji: '🐟', sentence: 'The stingray is flat.', sentenceZh: '黄貂鱼很扁。' },
      { en: 'Eel', phonetic: '/iːl/', zh: '鳗鱼', emoji: '🐍', sentence: 'The eel is long.', sentenceZh: '鳗鱼很长。' },
      { en: 'Clownfish', phonetic: '/ˈklaʊnfɪʃ/', zh: '小丑鱼', emoji: '🐠', sentence: 'The clownfish is orange.', sentenceZh: '小丑鱼是橙色的。' },
      { en: 'Goldfish', phonetic: '/ˈɡəʊldfɪʃ/', zh: '金鱼', emoji: '🐟', sentence: 'The goldfish is shiny.', sentenceZh: '金鱼闪闪发亮。' },
      { en: 'Tuna', phonetic: '/ˈtjuːnə/', zh: '金枪鱼', emoji: '🐟', sentence: 'The tuna is big.', sentenceZh: '金枪鱼很大。' },
      { en: 'Salmon', phonetic: '/ˈsæmən/', zh: '三文鱼', emoji: '🐟', sentence: 'The salmon jumps.', sentenceZh: '三文鱼会跳。' },
      { en: 'Seal', phonetic: '/siːl/', zh: '海豹', emoji: '🦭', sentence: 'The seal claps.', sentenceZh: '海豹会拍手。' },
      { en: 'Walrus', phonetic: '/ˈwɔːlrəs/', zh: '海象', emoji: '🦭', sentence: 'The walrus has tusks.', sentenceZh: '海象有长牙。' },
      { en: 'Otter', phonetic: '/ˈɒtər/', zh: '水獭', emoji: '🦦', sentence: 'The otter is cute.', sentenceZh: '水獭很可爱。' },
      { en: 'Swordfish', phonetic: '/ˈsɔːdfɪʃ/', zh: '剑鱼', emoji: '🗡️', sentence: 'The swordfish is fast.', sentenceZh: '剑鱼很快。' },
      { en: 'Pufferfish', phonetic: '/ˈpʌfəfɪʃ/', zh: '河豚', emoji: '🎈', sentence: 'The pufferfish puffs up.', sentenceZh: '河豚会鼓起来。' },
      { en: 'Angelfish', phonetic: '/ˈeɪndʒlfɪʃ/', zh: '神仙鱼', emoji: '🐠', sentence: 'The angelfish is pretty.', sentenceZh: '神仙鱼很漂亮。' },
      { en: 'Sea turtle', phonetic: '/siː ˈtɜːtl/', zh: '海龟', emoji: '🐢', sentence: 'The sea turtle swims slowly.', sentenceZh: '海龟游得慢。' },
      { en: 'Coral', phonetic: '/ˈkɒrəl/', zh: '珊瑚', emoji: '🪸', sentence: 'The coral is colorful.', sentenceZh: '珊瑚五颜六色。' },
      { en: 'Seaweed', phonetic: '/ˈsiːwiːd/', zh: '海草', emoji: '🌿', sentence: 'The seaweed is green.', sentenceZh: '海草是绿色的。' },
      { en: 'Sponge', phonetic: '/spʌndʒ/', zh: '海绵', emoji: '🧽', sentence: 'The sponge is soft.', sentenceZh: '海绵很软。' },
      { en: 'Plankton', phonetic: '/ˈplæŋktən/', zh: '浮游生物', emoji: '🦠', sentence: 'Plankton is tiny.', sentenceZh: '浮游生物很小。' },
      { en: 'Kelp', phonetic: '/kelp/', zh: '海带', emoji: '🌿', sentence: 'The kelp is long.', sentenceZh: '海带很长。' },
      { en: 'Manatee', phonetic: '/ˈmænətiː/', zh: '海牛', emoji: '🐋', sentence: 'The manatee is gentle.', sentenceZh: '海牛很温和。' },
      { en: 'Nautilus', phonetic: '/ˈnɔːtɪləs/', zh: '鹦鹉螺', emoji: '🐚', sentence: 'The nautilus has a shell.', sentenceZh: '鹦鹉螺有壳。' },
      { en: 'Abalone', phonetic: '/ˈæbələʊni/', zh: '鲍鱼', emoji: '🐚', sentence: 'The abalone is tasty.', sentenceZh: '鲍鱼很好吃。' },
      { en: 'Manta ray', phonetic: '/ˈmæntə reɪ/', zh: '魔鬼鱼', emoji: '🐟', sentence: 'The manta ray is huge.', sentenceZh: '魔鬼鱼很大。' },
      { en: 'Anglerfish', phonetic: '/ˈæŋɡləfɪʃ/', zh: '鮟鱇鱼', emoji: '🐟', sentence: 'The anglerfish has a light.', sentenceZh: '鮟鱇鱼会发光。' },
      { en: 'Hermit crab', phonetic: '/ˈhɜːmɪt kræb/', zh: '寄居蟹', emoji: '🦀', sentence: 'The hermit crab changes shells.', sentenceZh: '寄居蟹换壳住。' },
      { en: 'Sea lion', phonetic: '/siː ˈlaɪən/', zh: '海狮', emoji: '🦭', sentence: 'The sea lion barks.', sentenceZh: '海狮会叫。' }
    ]
  },
  {
    id: 'birds', level: 'starter', name: '🦜 鸟类', icon: '🦜',
    items: [
      { en: 'Robin', phonetic: '/ˈrɒbɪn/', zh: '知更鸟', emoji: '🐦', sentence: 'The robin is red.', sentenceZh: '知更鸟是红色的。' },
      { en: 'Sparrow', phonetic: '/ˈspærəʊ/', zh: '麻雀', emoji: '🐦', sentence: 'The sparrow is small.', sentenceZh: '麻雀很小。' },
      { en: 'Peacock', phonetic: '/ˈpiːkɒk/', zh: '孔雀', emoji: '🦚', sentence: 'The peacock is beautiful.', sentenceZh: '孔雀很漂亮。' },
      { en: 'Flamingo', phonetic: '/fləˈmɪŋɡəʊ/', zh: '火烈鸟', emoji: '🦩', sentence: 'The flamingo is pink.', sentenceZh: '火烈鸟是粉色的。' },
      { en: 'Swan', phonetic: '/swɒn/', zh: '天鹅', emoji: '🦢', sentence: 'The swan is white.', sentenceZh: '天鹅是白色的。' },
      { en: 'Goose', phonetic: '/ɡuːs/', zh: '鹅', emoji: '🪿', sentence: 'The goose is loud.', sentenceZh: '鹅叫声很大。' },
      { en: 'Crow', phonetic: '/krəʊ/', zh: '乌鸦', emoji: '🐦‍⬛', sentence: 'The crow is black.', sentenceZh: '乌鸦是黑色的。' },
      { en: 'Pigeon', phonetic: '/ˈpɪdʒɪn/', zh: '鸽子', emoji: '🐦', sentence: 'The pigeon coos.', sentenceZh: '鸽子会咕咕叫。' },
      { en: 'Seagull', phonetic: '/ˈsiːɡʌl/', zh: '海鸥', emoji: '🐦', sentence: 'The seagull flies by the sea.', sentenceZh: '海鸥在海边飞。' },
      { en: 'Woodpecker', phonetic: '/ˈwʊdpekər/', zh: '啄木鸟', emoji: '🐦', sentence: 'The woodpecker taps trees.', sentenceZh: '啄木鸟啄树。' },
      { en: 'Hummingbird', phonetic: '/ˈhʌmɪŋbɜːd/', zh: '蜂鸟', emoji: '🐦', sentence: 'The hummingbird is tiny.', sentenceZh: '蜂鸟很小。' },
      { en: 'Cardinal', phonetic: '/ˈkɑːdɪnl/', zh: '红雀', emoji: '🐦', sentence: 'The cardinal is bright red.', sentenceZh: '红雀是鲜红色的。' },
      { en: 'Canary', phonetic: '/kəˈneəri/', zh: '金丝雀', emoji: '🐦', sentence: 'The canary sings.', sentenceZh: '金丝雀会唱歌。' },
      { en: 'Finch', phonetic: '/fɪntʃ/', zh: '雀', emoji: '🐦', sentence: 'The finch is small.', sentenceZh: '雀很小。' },
      { en: 'Swallow', phonetic: '/ˈswɒləʊ/', zh: '燕子', emoji: '🐦', sentence: 'The swallow flies fast.', sentenceZh: '燕子飞得快。' },
      { en: 'Stork', phonetic: '/stɔːk/', zh: '鹳', emoji: '🐦', sentence: 'The stork has long legs.', sentenceZh: '鹳有长腿。' },
      { en: 'Pelican', phonetic: '/ˈpelɪkən/', zh: '鹈鹕', emoji: '🐦', sentence: 'The pelican has a big beak.', sentenceZh: '鹈鹕有大嘴。' },
      { en: 'Vulture', phonetic: '/ˈvʌltʃər/', zh: '秃鹫', emoji: '🐦', sentence: 'The vulture is big.', sentenceZh: '秃鹫很大。' },
      { en: 'Magpie', phonetic: '/ˈmæɡpaɪ/', zh: '喜鹊', emoji: '🐦', sentence: 'The magpie is black and white.', sentenceZh: '喜鹊是黑白相间的。' },
      { en: 'Nightingale', phonetic: '/ˈnaɪtɪŋɡeɪl/', zh: '夜莺', emoji: '🐦', sentence: 'The nightingale sings at night.', sentenceZh: '夜莺晚上唱歌。' },
      { en: 'Lark', phonetic: '/lɑːk/', zh: '云雀', emoji: '🐦', sentence: 'The lark sings high.', sentenceZh: '云雀在高处唱歌。' },
      { en: 'Raven', phonetic: '/ˈreɪvn/', zh: '渡鸦', emoji: '🐦‍⬛', sentence: 'The raven is clever.', sentenceZh: '渡鸦很聪明。' },
      { en: 'Toucan', phonetic: '/ˈtuːkæn/', zh: '巨嘴鸟', emoji: '🐦', sentence: 'The toucan has a big beak.', sentenceZh: '巨嘴鸟有大嘴。' },
      { en: 'Ostrich', phonetic: '/ˈɒstrɪtʃ/', zh: '鸵鸟', emoji: '🐦', sentence: 'The ostrich runs fast.', sentenceZh: '鸵鸟跑得快。' }
    ]
  },
  {
    id: 'drinks', level: 'starter', name: '🥤 饮品', icon: '🥤',
    items: [
      { en: 'Water', phonetic: '/ˈwɔːtər/', zh: '水', emoji: '💧', sentence: 'I drink water.', sentenceZh: '我喝水。' },
      { en: 'Milk', phonetic: '/mɪlk/', zh: '牛奶', emoji: '🥛', sentence: 'I drink milk.', sentenceZh: '我喝牛奶。' },
      { en: 'Juice', phonetic: '/dʒuːs/', zh: '果汁', emoji: '🧃', sentence: 'I like juice.', sentenceZh: '我喜欢果汁。' },
      { en: 'Tea', phonetic: '/tiː/', zh: '茶', emoji: '🍵', sentence: 'Grandpa drinks tea.', sentenceZh: '爷爷喝茶。' },
      { en: 'Coffee', phonetic: '/ˈkɒfi/', zh: '咖啡', emoji: '☕', sentence: 'Dad drinks coffee.', sentenceZh: '爸爸喝咖啡。' },
      { en: 'Soda', phonetic: '/ˈsəʊdə/', zh: '汽水', emoji: '🥤', sentence: 'Soda is bubbly.', sentenceZh: '汽水有气泡。' },
      { en: 'Soy milk', phonetic: '/sɔɪ mɪlk/', zh: '豆浆', emoji: '🥛', sentence: 'I drink soy milk.', sentenceZh: '我喝豆浆。' },
      { en: 'Yogurt', phonetic: '/ˈjɒɡət/', zh: '酸奶', emoji: '🥛', sentence: 'Yogurt is sour.', sentenceZh: '酸奶是酸的。' },
      { en: 'Soup', phonetic: '/suːp/', zh: '汤', emoji: '🥣', sentence: 'The soup is hot.', sentenceZh: '汤是热的。' },
      { en: 'Coconut water', phonetic: '/ˈkəʊkənʌt ˈwɔːtər/', zh: '椰子水', emoji: '🥥', sentence: 'Coconut water is sweet.', sentenceZh: '椰子水很甜。' },
      { en: 'Hot chocolate', phonetic: '/hɒt ˈtʃɒklət/', zh: '热巧克力', emoji: '🍫', sentence: 'Hot chocolate is warm.', sentenceZh: '热巧克力很暖。' },
      { en: 'Lemonade', phonetic: '/ˈleməneɪd/', zh: '柠檬水', emoji: '🍋', sentence: 'Lemonade is sour.', sentenceZh: '柠檬水是酸的。' },
      { en: 'Honey water', phonetic: '/ˈhʌni ˈwɔːtər/', zh: '蜂蜜水', emoji: '🍯', sentence: 'Honey water is sweet.', sentenceZh: '蜂蜜水很甜。' },
      { en: 'Smoothie', phonetic: '/ˈsmuːði/', zh: '冰沙', emoji: '🥤', sentence: 'The smoothie is cold.', sentenceZh: '冰沙很凉。' },
      { en: 'Cola', phonetic: '/ˈkəʊlə/', zh: '可乐', emoji: '🥤', sentence: 'Cola is sweet.', sentenceZh: '可乐很甜。' },
      { en: 'Milk tea', phonetic: '/mɪlk tiː/', zh: '奶茶', emoji: '🧋', sentence: 'Milk tea is popular.', sentenceZh: '奶茶很受欢迎。' },
      { en: 'Orange juice', phonetic: '/ˈɒrɪndʒ dʒuːs/', zh: '橙汁', emoji: '🍊', sentence: 'Orange juice is sweet.', sentenceZh: '橙汁很甜。' },
      { en: 'Apple juice', phonetic: '/ˈæpl dʒuːs/', zh: '苹果汁', emoji: '🍎', sentence: 'Apple juice is yummy.', sentenceZh: '苹果汁很好喝。' }
    ]
  },
  {
    id: 'snacks', level: 'starter', name: '🍩 零食点心', icon: '🍩',
    items: [
      { en: 'Cookie', phonetic: '/ˈkʊki/', zh: '饼干', emoji: '🍪', sentence: 'I like cookies.', sentenceZh: '我喜欢饼干。' },
      { en: 'Candy', phonetic: '/ˈkændi/', zh: '糖果', emoji: '🍬', sentence: 'Candy is sweet.', sentenceZh: '糖果是甜的。' },
      { en: 'Chocolate', phonetic: '/ˈtʃɒklət/', zh: '巧克力', emoji: '🍫', sentence: 'Chocolate is yummy.', sentenceZh: '巧克力很好吃。' },
      { en: 'Cake', phonetic: '/keɪk/', zh: '蛋糕', emoji: '🍰', sentence: 'The cake is sweet.', sentenceZh: '蛋糕很甜。' },
      { en: 'Donut', phonetic: '/ˈdəʊnʌt/', zh: '甜甜圈', emoji: '🍩', sentence: 'The donut has a hole.', sentenceZh: '甜甜圈有个洞。' },
      { en: 'Cupcake', phonetic: '/ˈkʌpkeɪk/', zh: '纸杯蛋糕', emoji: '🧁', sentence: 'The cupcake is pretty.', sentenceZh: '纸杯蛋糕很漂亮。' },
      { en: 'Ice cream', phonetic: '/aɪs kriːm/', zh: '冰淇淋', emoji: '🍦', sentence: 'Ice cream is cold.', sentenceZh: '冰淇淋是凉的。' },
      { en: 'Pudding', phonetic: '/ˈpʊdɪŋ/', zh: '布丁', emoji: '🍮', sentence: 'Pudding is soft.', sentenceZh: '布丁很软。' },
      { en: 'Chips', phonetic: '/tʃɪps/', zh: '薯片', emoji: '🍟', sentence: 'Chips are crispy.', sentenceZh: '薯片很脆。' },
      { en: 'Popcorn', phonetic: '/ˈpɒpkɔːn/', zh: '爆米花', emoji: '🍿', sentence: 'Popcorn is fun.', sentenceZh: '爆米花很有趣。' },
      { en: 'Pretzel', phonetic: '/ˈpretsl/', zh: '椒盐卷饼', emoji: '🥨', sentence: 'The pretzel is salty.', sentenceZh: '椒盐卷饼是咸的。' },
      { en: 'Marshmallow', phonetic: '/mɑːʃˈmæləʊ/', zh: '棉花糖', emoji: '🍡', sentence: 'The marshmallow is soft.', sentenceZh: '棉花糖很软。' },
      { en: 'Jelly', phonetic: '/ˈdʒeli/', zh: '果冻', emoji: '🍮', sentence: 'Jelly is jiggly.', sentenceZh: '果冻会晃。' },
      { en: 'Lollipop', phonetic: '/ˈlɒlipɒp/', zh: '棒棒糖', emoji: '🍭', sentence: 'The lollipop is sweet.', sentenceZh: '棒棒糖很甜。' },
      { en: 'Gum', phonetic: '/ɡʌm/', zh: '口香糖', emoji: '🍬', sentence: 'I chew gum.', sentenceZh: '我嚼口香糖。' },
      { en: 'Pancake', phonetic: '/ˈpænkeɪk/', zh: '煎饼', emoji: '🥞', sentence: 'The pancake is flat.', sentenceZh: '煎饼是扁的。' },
      { en: 'Waffle', phonetic: '/ˈwɒfl/', zh: '华夫饼', emoji: '🧇', sentence: 'The waffle is crispy.', sentenceZh: '华夫饼很脆。' },
      { en: 'Croissant', phonetic: '/ˈkrwæsɒ̃/', zh: '羊角面包', emoji: '🥐', sentence: 'The croissant is flaky.', sentenceZh: '羊角面包很酥。' },
      { en: 'Muffin', phonetic: '/ˈmʌfɪn/', zh: '玛芬', emoji: '🧁', sentence: 'The muffin is soft.', sentenceZh: '玛芬很软。' },
      { en: 'Biscuit', phonetic: '/ˈbɪskɪt/', zh: '小饼干', emoji: '🍪', sentence: 'The biscuit is crunchy.', sentenceZh: '小饼干很脆。' },
      { en: 'Nut', phonetic: '/nʌt/', zh: '坚果', emoji: '🥜', sentence: 'The nut is hard.', sentenceZh: '坚果很硬。' },
      { en: 'Raisin', phonetic: '/ˈreɪzn/', zh: '葡萄干', emoji: '🍇', sentence: 'The raisin is sweet.', sentenceZh: '葡萄干很甜。' },
      { en: 'Yogurt drop', phonetic: '/ˈjɒɡət drɒp/', zh: '酸奶豆', emoji: '🟡', sentence: 'The yogurt drop is tart.', sentenceZh: '酸奶豆有点酸。' },
      { en: 'Seaweed snack', phonetic: '/ˈsiːwiːd snæk/', zh: '海苔', emoji: '🌿', sentence: 'The seaweed snack is crispy.', sentenceZh: '海苔很脆。' }
    ]
  },
  {
    id: 'music', level: 'primary', name: '🎹 乐器', icon: '🎹',
    items: [
      { en: 'Piano', phonetic: '/piˈænəʊ/', zh: '钢琴', emoji: '🎹', sentence: 'I play the piano.', sentenceZh: '我弹钢琴。' },
      { en: 'Guitar', phonetic: '/ɡɪˈtɑːr/', zh: '吉他', emoji: '🎸', sentence: 'He plays the guitar.', sentenceZh: '他弹吉他。' },
      { en: 'Violin', phonetic: '/ˌvaɪəˈlɪn/', zh: '小提琴', emoji: '🎻', sentence: 'She plays the violin.', sentenceZh: '她拉小提琴。' },
      { en: 'Drum', phonetic: '/drʌm/', zh: '鼓', emoji: '🥁', sentence: 'I beat the drum.', sentenceZh: '我打鼓。' },
      { en: 'Flute', phonetic: '/fluːt/', zh: '长笛', emoji: '🪈', sentence: 'The flute is sweet.', sentenceZh: '长笛声音甜美。' },
      { en: 'Trumpet', phonetic: '/ˈtrʌmpɪt/', zh: '小号', emoji: '🎺', sentence: 'The trumpet is loud.', sentenceZh: '小号声音很大。' },
      { en: 'Harp', phonetic: '/hɑːp/', zh: '竖琴', emoji: '🪕', sentence: 'The harp is beautiful.', sentenceZh: '竖琴很美。' },
      { en: 'Saxophone', phonetic: '/ˈsæksəfəʊn/', zh: '萨克斯', emoji: '🎷', sentence: 'The saxophone is cool.', sentenceZh: '萨克斯很酷。' },
      { en: 'Accordion', phonetic: '/əˈkɔːdiən/', zh: '手风琴', emoji: '🪗', sentence: 'The accordion is fun.', sentenceZh: '手风琴很有趣。' },
      { en: 'Microphone', phonetic: '/ˈmaɪkrəfəʊn/', zh: '麦克风', emoji: '🎤', sentence: 'I sing into the microphone.', sentenceZh: '我对着麦克风唱歌。' },
      { en: 'Bell', phonetic: '/bel/', zh: '铃铛', emoji: '🔔', sentence: 'The bell rings.', sentenceZh: '铃铛会响。' },
      { en: 'Xylophone', phonetic: '/ˈzaɪləfəʊn/', zh: '木琴', emoji: '🎶', sentence: 'The xylophone is colorful.', sentenceZh: '木琴五颜六色。' },
      { en: 'Harmonica', phonetic: '/hɑːˈmɒnɪkə/', zh: '口琴', emoji: '🎵', sentence: 'The harmonica is small.', sentenceZh: '口琴很小。' },
      { en: 'Cello', phonetic: '/ˈtʃeləʊ/', zh: '大提琴', emoji: '🎻', sentence: 'The cello is big.', sentenceZh: '大提琴很大。' },
      { en: 'Banjo', phonetic: '/ˈbændʒəʊ/', zh: '班卓琴', emoji: '🪕', sentence: 'The banjo is fun.', sentenceZh: '班卓琴很有趣。' },
      { en: 'Maraca', phonetic: '/məˈrɑːkə/', zh: '沙锤', emoji: '🪇', sentence: 'I shake the maraca.', sentenceZh: '我摇沙锤。' },
      { en: 'Tambourine', phonetic: '/ˌtæmbəˈriːn/', zh: '铃鼓', emoji: '🪘', sentence: 'I shake the tambourine.', sentenceZh: '我摇铃鼓。' },
      { en: 'Cymbal', phonetic: '/ˈsɪmbl/', zh: '钹', emoji: '🥁', sentence: 'The cymbal crashes.', sentenceZh: '钹会哐哐响。' },
      { en: 'Keyboard', phonetic: '/ˈkiːbɔːd/', zh: '电子琴', emoji: '🎹', sentence: 'I play the keyboard.', sentenceZh: '我弹电子琴。' },
      { en: 'Note', phonetic: '/nəʊt/', zh: '音符', emoji: '🎵', sentence: 'I read the note.', sentenceZh: '我认音符。' }
    ]
  },
  {
    id: 'furniture', level: 'primary', name: '🛋️ 家具电器', icon: '🛋️',
    items: [
      { en: 'Sofa', phonetic: '/ˈsəʊfə/', zh: '沙发', emoji: '🛋️', sentence: 'I sit on the sofa.', sentenceZh: '我坐在沙发上。' },
      { en: 'Bed', phonetic: '/bed/', zh: '床', emoji: '🛏️', sentence: 'I sleep on my bed.', sentenceZh: '我睡在床上。' },
      { en: 'Table', phonetic: '/ˈteɪbl/', zh: '桌子', emoji: '🪑', sentence: 'The book is on the table.', sentenceZh: '书在桌子上。' },
      { en: 'Chair', phonetic: '/tʃeər/', zh: '椅子', emoji: '🪑', sentence: 'Sit on the chair.', sentenceZh: '坐在椅子上。' },
      { en: 'Desk', phonetic: '/desk/', zh: '书桌', emoji: '🗒️', sentence: 'I study at my desk.', sentenceZh: '我在书桌前学习。' },
      { en: 'Wardrobe', phonetic: '/ˈwɔːdrəʊb/', zh: '衣柜', emoji: '🚪', sentence: 'My clothes are in the wardrobe.', sentenceZh: '我的衣服在衣柜里。' },
      { en: 'Bookshelf', phonetic: '/ˈbʊkʃelf/', zh: '书架', emoji: '📚', sentence: 'The bookshelf is full.', sentenceZh: '书架是满的。' },
      { en: 'Dresser', phonetic: '/ˈdresər/', zh: '梳妆台', emoji: '🪞', sentence: 'The dresser has a mirror.', sentenceZh: '梳妆台有镜子。' },
      { en: 'Cabinet', phonetic: '/ˈkæbɪnət/', zh: '橱柜', emoji: '🗄️', sentence: 'The cabinet is tall.', sentenceZh: '橱柜很高。' },
      { en: 'Drawer', phonetic: '/drɔːr/', zh: '抽屉', emoji: '🗄️', sentence: 'I open the drawer.', sentenceZh: '我打开抽屉。' },
      { en: 'Shelf', phonetic: '/ʃelf/', zh: '架子', emoji: '🛒', sentence: 'The shelf is high.', sentenceZh: '架子很高。' },
      { en: 'TV', phonetic: '/ˌtiː ˈviː/', zh: '电视', emoji: '📺', sentence: 'I watch TV.', sentenceZh: '我看电视。' },
      { en: 'Fridge', phonetic: '/frɪdʒ/', zh: '冰箱', emoji: '🧊', sentence: 'The milk is in the fridge.', sentenceZh: '牛奶在冰箱里。' },
      { en: 'Oven', phonetic: '/ˈʌvn/', zh: '烤箱', emoji: '♨️', sentence: 'Mom uses the oven.', sentenceZh: '妈妈用烤箱。' },
      { en: 'Microwave', phonetic: '/ˈmaɪkrəweɪv/', zh: '微波炉', emoji: '🔆', sentence: 'I heat food in the microwave.', sentenceZh: '我用微波炉热饭。' },
      { en: 'Fan', phonetic: '/fæn/', zh: '风扇', emoji: '🌀', sentence: 'The fan is cool.', sentenceZh: '风扇很凉快。' },
      { en: 'Lamp', phonetic: '/læmp/', zh: '台灯', emoji: '💡', sentence: 'I turn on the lamp.', sentenceZh: '我打开台灯。' },
      { en: 'Carpet', phonetic: '/ˈkɑːpɪt/', zh: '地毯', emoji: '🟥', sentence: 'The carpet is soft.', sentenceZh: '地毯很软。' },
      { en: 'Curtain', phonetic: '/ˈkɜːtn/', zh: '窗帘', emoji: '🪟', sentence: 'I close the curtain.', sentenceZh: '我拉上窗帘。' },
      { en: 'Mirror', phonetic: '/ˈmɪrər/', zh: '镜子', emoji: '🪞', sentence: 'I look in the mirror.', sentenceZh: '我照镜子。' },
      { en: 'Clock', phonetic: '/klɒk/', zh: '时钟', emoji: '🕐', sentence: 'The clock ticks.', sentenceZh: '时钟滴答响。' },
      { en: 'Washing machine', phonetic: '/ˈwɒʃɪŋ məˈʃiːn/', zh: '洗衣机', emoji: '🧺', sentence: 'The washing machine is loud.', sentenceZh: '洗衣机声音很大。' }
    ]
  },
  {
    id: 'plants', level: 'primary', name: '🪴 植物', icon: '🪴',
    items: [
      { en: 'Plant', phonetic: '/plɑːnt/', zh: '植物', emoji: '🪴', sentence: 'I water the plant.', sentenceZh: '我给植物浇水。' },
      { en: 'Tree', phonetic: '/triː/', zh: '树', emoji: '🌳', sentence: 'The tree gives shade.', sentenceZh: '树能乘凉。' },
      { en: 'Flower', phonetic: '/ˈflaʊər/', zh: '花', emoji: '🌷', sentence: 'The flower blooms.', sentenceZh: '花开了。' },
      { en: 'Grass', phonetic: '/ɡrɑːs/', zh: '草', emoji: '🌱', sentence: 'The grass grows.', sentenceZh: '草在生长。' },
      { en: 'Leaf', phonetic: '/liːf/', zh: '树叶', emoji: '🍃', sentence: 'The leaf falls.', sentenceZh: '树叶落下来。' },
      { en: 'Root', phonetic: '/ruːt/', zh: '根', emoji: '🌱', sentence: 'The root drinks water.', sentenceZh: '根吸收水分。' },
      { en: 'Seed', phonetic: '/siːd/', zh: '种子', emoji: '🌰', sentence: 'I plant a seed.', sentenceZh: '我种下种子。' },
      { en: 'Sprout', phonetic: '/spraʊt/', zh: '芽', emoji: '🌱', sentence: 'The sprout is tiny.', sentenceZh: '芽很小。' },
      { en: 'Trunk', phonetic: '/trʌŋk/', zh: '树干', emoji: '🪵', sentence: 'The trunk is thick.', sentenceZh: '树干很粗。' },
      { en: 'Branch', phonetic: '/brɑːntʃ/', zh: '树枝', emoji: '🌿', sentence: 'The bird sits on a branch.', sentenceZh: '鸟停在树枝上。' },
      { en: 'Thorn', phonetic: '/θɔːn/', zh: '刺', emoji: '🌵', sentence: 'The thorn is sharp.', sentenceZh: '刺很尖。' },
      { en: 'Petal', phonetic: '/ˈpetl/', zh: '花瓣', emoji: '🌸', sentence: 'The petal is soft.', sentenceZh: '花瓣很软。' },
      { en: 'Bud', phonetic: '/bʌd/', zh: '花苞', emoji: '🌷', sentence: 'The bud will open.', sentenceZh: '花苞要开了。' },
      { en: 'Pollen', phonetic: '/ˈpɒlən/', zh: '花粉', emoji: '🟡', sentence: 'The pollen is yellow.', sentenceZh: '花粉是黄色的。' },
      { en: 'Mushroom', phonetic: '/ˈmʌʃruːm/', zh: '蘑菇', emoji: '🍄', sentence: 'The mushroom is small.', sentenceZh: '蘑菇很小。' },
      { en: 'Cactus', phonetic: '/ˈkæktəs/', zh: '仙人掌', emoji: '🌵', sentence: 'The cactus needs little water.', sentenceZh: '仙人掌不需要多少水。' },
      { en: 'Fern', phonetic: '/fɜːn/', zh: '蕨类', emoji: '🌿', sentence: 'The fern is green.', sentenceZh: '蕨类是绿色的。' },
      { en: 'Vine', phonetic: '/vaɪn/', zh: '藤', emoji: '🌿', sentence: 'The vine climbs up.', sentenceZh: '藤向上爬。' },
      { en: 'Weed', phonetic: '/wiːd/', zh: '杂草', emoji: '🌾', sentence: 'I pull the weed.', sentenceZh: '我拔杂草。' },
      { en: 'Crop', phonetic: '/krɒp/', zh: '庄稼', emoji: '🌾', sentence: 'The crop grows in the field.', sentenceZh: '庄稼长在田里。' },
      { en: 'Grain', phonetic: '/ɡreɪn/', zh: '谷物', emoji: '🌾', sentence: 'The grain is golden.', sentenceZh: '谷物是金色的。' },
      { en: 'Berry', phonetic: '/ˈberi/', zh: '浆果', emoji: '🫐', sentence: 'The berry is sweet.', sentenceZh: '浆果很甜。' }
    ]
  },
  {
    id: 'adjectives', level: 'primary', name: '✨ 形容词', icon: '✨',
    items: [
      { en: 'Big', phonetic: '/bɪɡ/', zh: '大的', emoji: '🐘', sentence: 'The elephant is big.', sentenceZh: '大象很大。' },
      { en: 'Small', phonetic: '/smɔːl/', zh: '小的', emoji: '🐭', sentence: 'The mouse is small.', sentenceZh: '老鼠很小。' },
      { en: 'Tall', phonetic: '/tɔːl/', zh: '高的', emoji: '🦒', sentence: 'The giraffe is tall.', sentenceZh: '长颈鹿很高。' },
      { en: 'Short', phonetic: '/ʃɔːt/', zh: '矮的', emoji: '🐭', sentence: 'The mouse is short.', sentenceZh: '老鼠很矮。' },
      { en: 'Long', phonetic: '/lɒŋ/', zh: '长的', emoji: '🐍', sentence: 'The snake is long.', sentenceZh: '蛇很长。' },
      { en: 'Fast', phonetic: '/fɑːst/', zh: '快的', emoji: '🐆', sentence: 'The cheetah is fast.', sentenceZh: '猎豹很快。' },
      { en: 'Slow', phonetic: '/sləʊ/', zh: '慢的', emoji: '🐢', sentence: 'The turtle is slow.', sentenceZh: '乌龟很慢。' },
      { en: 'Hot', phonetic: '/hɒt/', zh: '热的', emoji: '🔥', sentence: 'The fire is hot.', sentenceZh: '火很热。' },
      { en: 'Cold', phonetic: '/kəʊld/', zh: '冷的', emoji: '❄️', sentence: 'The ice is cold.', sentenceZh: '冰很冷。' },
      { en: 'Warm', phonetic: '/wɔːm/', zh: '温暖的', emoji: '☀️', sentence: 'The sun is warm.', sentenceZh: '太阳很温暖。' },
      { en: 'Cool', phonetic: '/kuːl/', zh: '凉爽的', emoji: '🌬️', sentence: 'The wind is cool.', sentenceZh: '风很凉爽。' },
      { en: 'Sweet', phonetic: '/swiːt/', zh: '甜的', emoji: '🍬', sentence: 'The candy is sweet.', sentenceZh: '糖果是甜的。' },
      { en: 'Sour', phonetic: '/ˈsaʊər/', zh: '酸的', emoji: '🍋', sentence: 'The lemon is sour.', sentenceZh: '柠檬是酸的。' },
      { en: 'Bitter', phonetic: '/ˈbɪtər/', zh: '苦的', emoji: '☕', sentence: 'Coffee is bitter.', sentenceZh: '咖啡是苦的。' },
      { en: 'Spicy', phonetic: '/ˈspaɪsi/', zh: '辣的', emoji: '🌶️', sentence: 'The pepper is spicy.', sentenceZh: '辣椒是辣的。' },
      { en: 'Salty', phonetic: '/ˈsɔːlti/', zh: '咸的', emoji: '🧂', sentence: 'The chips are salty.', sentenceZh: '薯片是咸的。' },
      { en: 'Soft', phonetic: '/sɒft/', zh: '软的', emoji: '🧸', sentence: 'The bear is soft.', sentenceZh: '小熊很软。' },
      { en: 'Hard', phonetic: '/hɑːd/', zh: '硬的', emoji: '🪨', sentence: 'The rock is hard.', sentenceZh: '石头很硬。' },
      { en: 'Smooth', phonetic: '/smuːð/', zh: '光滑的', emoji: '🥚', sentence: 'The egg is smooth.', sentenceZh: '鸡蛋很光滑。' },
      { en: 'Rough', phonetic: '/rʌf/', zh: '粗糙的', emoji: '🌲', sentence: 'The bark is rough.', sentenceZh: '树皮很粗糙。' },
      { en: 'Heavy', phonetic: '/ˈhevi/', zh: '重的', emoji: '🪨', sentence: 'The rock is heavy.', sentenceZh: '石头很重。' },
      { en: 'Light', phonetic: '/laɪt/', zh: '轻的', emoji: '🪶', sentence: 'The feather is light.', sentenceZh: '羽毛很轻。' },
      { en: 'Clean', phonetic: '/kliːn/', zh: '干净的', emoji: '✨', sentence: 'My hands are clean.', sentenceZh: '我的手很干净。' },
      { en: 'Dirty', phonetic: '/ˈdɜːti/', zh: '脏的', emoji: '💩', sentence: 'My shoes are dirty.', sentenceZh: '我的鞋很脏。' },
      { en: 'Wet', phonetic: '/wet/', zh: '湿的', emoji: '💧', sentence: 'The towel is wet.', sentenceZh: '毛巾是湿的。' },
      { en: 'Dry', phonetic: '/draɪ/', zh: '干的', emoji: '🏜️', sentence: 'The sand is dry.', sentenceZh: '沙子是干的。' },
      { en: 'New', phonetic: '/njuː/', zh: '新的', emoji: '🆕', sentence: 'My toy is new.', sentenceZh: '我的玩具是新的。' },
      { en: 'Old', phonetic: '/əʊld/', zh: '旧的', emoji: '📦', sentence: 'The book is old.', sentenceZh: '这本书很旧。' },
      { en: 'Good', phonetic: '/ɡʊd/', zh: '好的', emoji: '👍', sentence: 'The food is good.', sentenceZh: '食物很好。' },
      { en: 'Bad', phonetic: '/bæd/', zh: '坏的', emoji: '👎', sentence: 'The apple is bad.', sentenceZh: '苹果坏了。' },
      { en: 'Beautiful', phonetic: '/ˈbjuːtɪfl/', zh: '美丽的', emoji: '🌸', sentence: 'The flower is beautiful.', sentenceZh: '花很美丽。' },
      { en: 'Ugly', phonetic: '/ˈʌɡli/', zh: '丑的', emoji: '🤢', sentence: 'The toad is ugly.', sentenceZh: '蟾蜍很丑。' },
      { en: 'Strong', phonetic: '/strɒŋ/', zh: '强壮的', emoji: '💪', sentence: 'The lion is strong.', sentenceZh: '狮子很强壮。' },
      { en: 'Weak', phonetic: '/wiːk/', zh: '虚弱的', emoji: '😶', sentence: 'The kitten is weak.', sentenceZh: '小猫很虚弱。' },
      { en: 'Loud', phonetic: '/laʊd/', zh: '大声的', emoji: '🔊', sentence: 'The drum is loud.', sentenceZh: '鼓声很大。' },
      { en: 'Quiet', phonetic: '/ˈkwaɪət/', zh: '安静的', emoji: '🤫', sentence: 'The night is quiet.', sentenceZh: '夜晚很安静。' },
      { en: 'Bright', phonetic: '/braɪt/', zh: '明亮的', emoji: '💡', sentence: 'The sun is bright.', sentenceZh: '太阳很明亮。' },
      { en: 'Dark', phonetic: '/dɑːk/', zh: '黑暗的', emoji: '🌑', sentence: 'The cave is dark.', sentenceZh: '洞穴很黑。' },
      { en: 'Empty', phonetic: '/ˈempti/', zh: '空的', emoji: '🫙', sentence: 'The cup is empty.', sentenceZh: '杯子是空的。' },
      { en: 'Full', phonetic: '/fʊl/', zh: '满的', emoji: '🥛', sentence: 'The cup is full.', sentenceZh: '杯子是满的。' }
    ]
  },
  {
    id: 'verbs2', level: 'primary', name: '🏃 更多动作', icon: '🏃',
    items: [
      { en: 'Think', phonetic: '/θɪŋk/', zh: '思考', emoji: '🤔', sentence: 'I think hard.', sentenceZh: '我认真思考。' },
      { en: 'Remember', phonetic: '/rɪˈmembər/', zh: '记得', emoji: '🧠', sentence: 'I remember it.', sentenceZh: '我记得。' },
      { en: 'Forget', phonetic: '/fəˈɡet/', zh: '忘记', emoji: '🙈', sentence: 'I forget it.', sentenceZh: '我忘了。' },
      { en: 'Learn', phonetic: '/lɜːn/', zh: '学习', emoji: '📖', sentence: 'I learn English.', sentenceZh: '我学英语。' },
      { en: 'Teach', phonetic: '/tiːtʃ/', zh: '教', emoji: '👩‍🏫', sentence: 'She teaches me.', sentenceZh: '她教我。' },
      { en: 'Count', phonetic: '/kaʊnt/', zh: '数数', emoji: '🔢', sentence: 'I count to ten.', sentenceZh: '我数到十。' },
      { en: 'Add', phonetic: '/æd/', zh: '加', emoji: '➕', sentence: 'I add them up.', sentenceZh: '我把它们加起来。' },
      { en: 'Build', phonetic: '/bɪld/', zh: '建造', emoji: '🏗️', sentence: 'I build a tower.', sentenceZh: '我搭一座塔。' },
      { en: 'Fix', phonetic: '/fɪks/', zh: '修理', emoji: '🔧', sentence: 'Dad fixes the toy.', sentenceZh: '爸爸修玩具。' },
      { en: 'Break', phonetic: '/breɪk/', zh: '弄坏', emoji: '💔', sentence: 'I break the cup.', sentenceZh: '我打碎了杯子。' },
      { en: 'Carry', phonetic: '/ˈkæri/', zh: '搬运', emoji: '📦', sentence: 'I carry the box.', sentenceZh: '我搬箱子。' },
      { en: 'Lift', phonetic: '/lɪft/', zh: '举起', emoji: '🏋️', sentence: 'I lift the ball.', sentenceZh: '我举起球。' },
      { en: 'Drop', phonetic: '/drɒp/', zh: '掉下', emoji: '⬇️', sentence: 'I drop the apple.', sentenceZh: '我把苹果掉了。' },
      { en: 'Pick', phonetic: '/pɪk/', zh: '捡起', emoji: '✋', sentence: 'I pick a flower.', sentenceZh: '我摘一朵花。' },
      { en: 'Touch', phonetic: '/tʌtʃ/', zh: '触摸', emoji: '👆', sentence: 'I touch the cat.', sentenceZh: '我摸猫。' },
      { en: 'Hold', phonetic: '/həʊld/', zh: '握住', emoji: '✊', sentence: 'I hold the pen.', sentenceZh: '我握住笔。' },
      { en: 'Give', phonetic: '/ɡɪv/', zh: '给', emoji: '🎁', sentence: 'I give you a gift.', sentenceZh: '我给你礼物。' },
      { en: 'Take', phonetic: '/teɪk/', zh: '拿', emoji: '🤲', sentence: 'I take the book.', sentenceZh: '我拿书。' },
      { en: 'Send', phonetic: '/send/', zh: '发送', emoji: '📨', sentence: 'I send a letter.', sentenceZh: '我寄信。' },
      { en: 'Buy', phonetic: '/baɪ/', zh: '买', emoji: '🛒', sentence: 'I buy bread.', sentenceZh: '我买面包。' },
      { en: 'Sell', phonetic: '/sel/', zh: '卖', emoji: '🏷️', sentence: 'They sell fruit.', sentenceZh: '他们卖水果。' },
      { en: 'Pay', phonetic: '/peɪ/', zh: '付款', emoji: '💳', sentence: 'I pay for it.', sentenceZh: '我付钱。' },
      { en: 'Try', phonetic: '/traɪ/', zh: '尝试', emoji: '💪', sentence: 'I try again.', sentenceZh: '我再试一次。' },
      { en: 'Stop', phonetic: '/stɒp/', zh: '停止', emoji: '✋', sentence: 'Please stop.', sentenceZh: '请停下。' },
      { en: 'Start', phonetic: '/stɑːt/', zh: '开始', emoji: '▶️', sentence: 'Let us start.', sentenceZh: '我们开始吧。' },
      { en: 'Turn', phonetic: '/tɜːn/', zh: '转动', emoji: '🔄', sentence: 'I turn the page.', sentenceZh: '我翻页。' },
      { en: 'Cut', phonetic: '/kʌt/', zh: '切', emoji: '✂️', sentence: 'I cut the apple.', sentenceZh: '我切苹果。' },
      { en: 'Mix', phonetic: '/mɪks/', zh: '混合', emoji: '🥣', sentence: 'I mix the dough.', sentenceZh: '我和面。' },
      { en: 'Pour', phonetic: '/pɔːr/', zh: '倒', emoji: '🫗', sentence: 'I pour the milk.', sentenceZh: '我倒牛奶。' },
      { en: 'Stir', phonetic: '/stɜːr/', zh: '搅拌', emoji: '🥄', sentence: 'I stir the soup.', sentenceZh: '我搅汤。' },
      { en: 'Plant', phonetic: '/plɑːnt/', zh: '种植', emoji: '🌱', sentence: 'I plant a tree.', sentenceZh: '我种树。' },
      { en: 'Water', phonetic: '/ˈwɔːtər/', zh: '浇水', emoji: '💧', sentence: 'I water the flowers.', sentenceZh: '我浇花。' },
      { en: 'Grow', phonetic: '/ɡrəʊ/', zh: '生长', emoji: '📈', sentence: 'Plants grow.', sentenceZh: '植物会生长。' },
      { en: 'Find', phonetic: '/faɪnd/', zh: '找到', emoji: '🔎', sentence: 'I find a coin.', sentenceZh: '我找到一枚硬币。' },
      { en: 'Hide', phonetic: '/haɪd/', zh: '躲藏', emoji: '🙈', sentence: 'I hide here.', sentenceZh: '我藏在这里。' },
      { en: 'Seek', phonetic: '/siːk/', zh: '寻找', emoji: '👁️', sentence: 'Ready or not, I seek.', sentenceZh: '藏好了吗我来找。' },
      { en: 'Show', phonetic: '/ʃəʊ/', zh: '展示', emoji: '👉', sentence: 'I show you.', sentenceZh: '我给你看。' },
      { en: 'Watch', phonetic: '/wɒtʃ/', zh: '观看', emoji: '👀', sentence: 'I watch TV.', sentenceZh: '我看电视。' },
      { en: 'Listen', phonetic: '/ˈlɪsn/', zh: '听', emoji: '👂', sentence: 'I listen to music.', sentenceZh: '我听音乐。' },
      { en: 'Smell', phonetic: '/smel/', zh: '闻', emoji: '👃', sentence: 'I smell the flower.', sentenceZh: '我闻花。' },
      { en: 'Taste', phonetic: '/teɪst/', zh: '尝', emoji: '👅', sentence: 'I taste the soup.', sentenceZh: '我尝汤。' }
    ]
  },
  {
    id: 'tools', level: 'primary', name: '🔧 工具', icon: '🔧',
    items: [
      { en: 'Hammer', phonetic: '/ˈhæmər/', zh: '锤子', emoji: '🔨', sentence: 'I use a hammer.', sentenceZh: '我用锤子。' },
      { en: 'Screwdriver', phonetic: '/ˈskruːdraɪvər/', zh: '螺丝刀', emoji: '🪛', sentence: 'Dad uses a screwdriver.', sentenceZh: '爸爸用螺丝刀。' },
      { en: 'Wrench', phonetic: '/rentʃ/', zh: '扳手', emoji: '🔧', sentence: 'The wrench is big.', sentenceZh: '扳手很大。' },
      { en: 'Saw', phonetic: '/sɔː/', zh: '锯子', emoji: '🪚', sentence: 'The saw is sharp.', sentenceZh: '锯子很锋利。' },
      { en: 'Nail', phonetic: '/neɪl/', zh: '钉子', emoji: '📌', sentence: 'I hit the nail.', sentenceZh: '我钉钉子。' },
      { en: 'Screw', phonetic: '/skruː/', zh: '螺丝', emoji: '🔩', sentence: 'I turn the screw.', sentenceZh: '我拧螺丝。' },
      { en: 'Tape', phonetic: '/teɪp/', zh: '胶带', emoji: '🩹', sentence: 'I use tape.', sentenceZh: '我用胶带。' },
      { en: 'Brush', phonetic: '/brʌʃ/', zh: '刷子', emoji: '🖌️', sentence: 'I paint with a brush.', sentenceZh: '我用刷子刷。' },
      { en: 'Broom', phonetic: '/bruːm/', zh: '扫帚', emoji: '🧹', sentence: 'I sweep with a broom.', sentenceZh: '我用扫帚扫地。' },
      { en: 'Mop', phonetic: '/mɒp/', zh: '拖把', emoji: '🧽', sentence: 'I mop the floor.', sentenceZh: '我拖地。' },
      { en: 'Bucket', phonetic: '/ˈbʌkɪt/', zh: '水桶', emoji: '🪣', sentence: 'The bucket is full.', sentenceZh: '水桶是满的。' },
      { en: 'Ladder', phonetic: '/ˈlædər/', zh: '梯子', emoji: '🪜', sentence: 'I climb the ladder.', sentenceZh: '我爬梯子。' },
      { en: 'Shovel', phonetic: '/ˈʃʌvl/', zh: '铲子', emoji: '🪏', sentence: 'I dig with a shovel.', sentenceZh: '我用铲子挖。' },
      { en: 'Flashlight', phonetic: '/ˈflæʃlaɪt/', zh: '手电筒', emoji: '🔦', sentence: 'The flashlight is bright.', sentenceZh: '手电筒很亮。' },
      { en: 'Lock', phonetic: '/lɒk/', zh: '锁', emoji: '🔒', sentence: 'I lock the door.', sentenceZh: '我锁门。' },
      { en: 'Key', phonetic: '/kiː/', zh: '钥匙', emoji: '🔑', sentence: 'I have the key.', sentenceZh: '我有钥匙。' }
    ]
  },
  {
    id: 'classroom', level: 'primary', name: '🏫 课堂用语', icon: '🏫',
    items: [
      { en: 'Listen', phonetic: '/ˈlɪsn/', zh: '听', emoji: '👂', sentence: 'Listen to the teacher.', sentenceZh: '听老师讲。' },
      { en: 'Look', phonetic: '/lʊk/', zh: '看', emoji: '👀', sentence: 'Look at the board.', sentenceZh: '看黑板。' },
      { en: 'Read', phonetic: '/riːd/', zh: '读', emoji: '📖', sentence: 'Read the sentence.', sentenceZh: '读句子。' },
      { en: 'Write', phonetic: '/raɪt/', zh: '写', emoji: '✍️', sentence: 'Write your name.', sentenceZh: '写你的名字。' },
      { en: 'Spell', phonetic: '/spel/', zh: '拼写', emoji: '🔤', sentence: 'Spell the word.', sentenceZh: '拼写单词。' },
      { en: 'Count', phonetic: '/kaʊnt/', zh: '数', emoji: '🔢', sentence: 'Count the apples.', sentenceZh: '数苹果。' },
      { en: 'Draw', phonetic: '/drɔː/', zh: '画', emoji: '🎨', sentence: 'Draw a picture.', sentenceZh: '画一幅画。' },
      { en: 'Color', phonetic: '/ˈkʌlər/', zh: '涂色', emoji: '🖍️', sentence: 'Color the picture.', sentenceZh: '给画涂色。' },
      { en: 'Cut', phonetic: '/kʌt/', zh: '剪', emoji: '✂️', sentence: 'Cut the paper.', sentenceZh: '剪纸。' },
      { en: 'Glue', phonetic: '/ɡluː/', zh: '粘', emoji: '🧴', sentence: 'Glue them together.', sentenceZh: '把它们粘在一起。' },
      { en: 'Raise hand', phonetic: '/reɪz hænd/', zh: '举手', emoji: '✋', sentence: 'Raise your hand.', sentenceZh: '举手。' },
      { en: 'Stand up', phonetic: '/stænd ʌp/', zh: '起立', emoji: '🧍', sentence: 'Stand up, please.', sentenceZh: '请起立。' },
      { en: 'Sit down', phonetic: '/sɪt daʊn/', zh: '坐下', emoji: '🪑', sentence: 'Sit down, please.', sentenceZh: '请坐下。' },
      { en: 'Open', phonetic: '/ˈəʊpən/', zh: '打开', emoji: '📂', sentence: 'Open your book.', sentenceZh: '打开书。' },
      { en: 'Close', phonetic: '/kləʊz/', zh: '合上', emoji: '📕', sentence: 'Close your book.', sentenceZh: '合上书。' },
      { en: 'Repeat', phonetic: '/rɪˈpiːt/', zh: '重复', emoji: '🔁', sentence: 'Repeat after me.', sentenceZh: '跟我读。' },
      { en: 'Match', phonetic: '/mætʃ/', zh: '配对', emoji: '🔗', sentence: 'Match the words.', sentenceZh: '给单词配对。' },
      { en: 'Circle', phonetic: '/ˈsɜːkl/', zh: '圈出', emoji: '⭕', sentence: 'Circle the answer.', sentenceZh: '圈出答案。' },
      { en: 'Answer', phonetic: '/ˈɑːnsər/', zh: '回答', emoji: '🙋', sentence: 'Answer the question.', sentenceZh: '回答问题。' },
      { en: 'Question', phonetic: '/ˈkwestʃən/', zh: '问题', emoji: '❓', sentence: 'I have a question.', sentenceZh: '我有个问题。' },
      { en: 'Group', phonetic: '/ɡruːp/', zh: '小组', emoji: '👥', sentence: 'Make a group.', sentenceZh: '组成小组。' }
    ]
  },
  {
    id: 'space', level: 'primary', name: '🚀 太空探索', icon: '🚀',
    items: [
      { en: 'Rocket', phonetic: '/ˈrɒkɪt/', zh: '火箭', emoji: '🚀', sentence: 'The rocket flies high.', sentenceZh: '火箭飞得高。' },
      { en: 'Astronaut', phonetic: '/ˈæstrənɔːt/', zh: '宇航员', emoji: '👨‍🚀', sentence: 'The astronaut goes to space.', sentenceZh: '宇航员去太空。' },
      { en: 'Planet', phonetic: '/ˈplænɪt/', zh: '行星', emoji: '🪐', sentence: 'The planet is round.', sentenceZh: '行星是圆的。' },
      { en: 'Galaxy', phonetic: '/ˈɡæləksi/', zh: '星系', emoji: '🌌', sentence: 'The galaxy is big.', sentenceZh: '星系很大。' },
      { en: 'Comet', phonetic: '/ˈkɒmɪt/', zh: '彗星', emoji: '☄️', sentence: 'The comet has a tail.', sentenceZh: '彗星有尾巴。' },
      { en: 'Satellite', phonetic: '/ˈsætəlaɪt/', zh: '卫星', emoji: '🛰️', sentence: 'The satellite spins.', sentenceZh: '卫星在旋转。' },
      { en: 'Telescope', phonetic: '/ˈtelɪskəʊp/', zh: '望远镜', emoji: '🔭', sentence: 'I look through a telescope.', sentenceZh: '我用望远镜看。' },
      { en: 'Alien', phonetic: '/ˈeɪliən/', zh: '外星人', emoji: '👽', sentence: 'The alien is green.', sentenceZh: '外星人是绿色的。' },
      { en: 'Earth', phonetic: '/ɜːθ/', zh: '地球', emoji: '🌍', sentence: 'We live on Earth.', sentenceZh: '我们住在地球。' },
      { en: 'Mars', phonetic: '/mɑːz/', zh: '火星', emoji: '🔴', sentence: 'Mars is red.', sentenceZh: '火星是红色的。' },
      { en: 'Jupiter', phonetic: '/ˈdʒuːpɪtər/', zh: '木星', emoji: '🟠', sentence: 'Jupiter is big.', sentenceZh: '木星很大。' },
      { en: 'Saturn', phonetic: '/ˈsætɜːn/', zh: '土星', emoji: '🪐', sentence: 'Saturn has rings.', sentenceZh: '土星有光环。' },
      { en: 'Venus', phonetic: '/ˈviːnəs/', zh: '金星', emoji: '🟡', sentence: 'Venus is hot.', sentenceZh: '金星很热。' },
      { en: 'Neptune', phonetic: '/ˈneptjuːn/', zh: '海王星', emoji: '🔵', sentence: 'Neptune is blue.', sentenceZh: '海王星是蓝色的。' },
      { en: 'Spaceship', phonetic: '/ˈspeɪsʃɪp/', zh: '宇宙飞船', emoji: '🛸', sentence: 'The spaceship flies.', sentenceZh: '宇宙飞船在飞。' },
      { en: 'Orbit', phonetic: '/ˈɔːbɪt/', zh: '轨道', emoji: '🔄', sentence: 'The moon orbits Earth.', sentenceZh: '月亮绕着地球转。' },
      { en: 'Gravity', phonetic: '/ˈɡrævəti/', zh: '引力', emoji: '⬇️', sentence: 'Gravity pulls us down.', sentenceZh: '引力把我们往下拉。' },
      { en: 'Universe', phonetic: '/ˈjuːnɪvɜːs/', zh: '宇宙', emoji: '🌠', sentence: 'The universe is huge.', sentenceZh: '宇宙很大。' },
      { en: 'Meteor', phonetic: '/ˈmiːtiər/', zh: '流星', emoji: '💫', sentence: 'The meteor falls.', sentenceZh: '流星落下来。' },
      { en: 'Spacesuit', phonetic: '/ˈspeɪssuːt/', zh: '宇航服', emoji: '🧑‍🚀', sentence: 'He wears a spacesuit.', sentenceZh: '他穿着宇航服。' },
      { en: 'Rover', phonetic: '/ˈrəʊvər/', zh: '探测车', emoji: '🚙', sentence: 'The rover drives on Mars.', sentenceZh: '探测车在火星上开。' },
      { en: 'Black hole', phonetic: '/blæk həʊl/', zh: '黑洞', emoji: '⚫', sentence: 'A black hole is dark.', sentenceZh: '黑洞很黑。' },
      { en: 'Nebula', phonetic: '/ˈnebjələ/', zh: '星云', emoji: '🌌', sentence: 'The nebula is colorful.', sentenceZh: '星云五颜六色。' },
      { en: 'Aurora', phonetic: '/ɔːˈrɔːrə/', zh: '极光', emoji: '🌅', sentence: 'The aurora is pretty.', sentenceZh: '极光很漂亮。' },
      { en: 'Solar system', phonetic: '/ˈsəʊlə ˈsɪstəm/', zh: '太阳系', emoji: '🌞', sentence: 'The solar system has eight planets.', sentenceZh: '太阳系有八大行星。' },
      { en: 'Asteroid', phonetic: '/ˈæstərɔɪd/', zh: '小行星', emoji: '🪨', sentence: 'The asteroid floats.', sentenceZh: '小行星漂浮着。' },
      { en: 'UFO', phonetic: '/ˌjuː ef ˈəʊ/', zh: '飞碟', emoji: '🛸', sentence: 'The UFO is mysterious.', sentenceZh: '飞碟很神秘。' },
      { en: 'Space station', phonetic: '/speɪs ˈsteɪʃn/', zh: '空间站', emoji: '📡', sentence: 'The space station is in space.', sentenceZh: '空间站在太空中。' },
      { en: 'Moon rock', phonetic: '/muːn rɒk/', zh: '月球岩石', emoji: '🌑', sentence: 'The moon rock is gray.', sentenceZh: '月球岩石是灰色的。' },
      { en: 'Shooting star', phonetic: '/ˈʃuːtɪŋ stɑːr/', zh: '流星', emoji: '🌠', sentence: 'I see a shooting star.', sentenceZh: '我看到一颗流星。' },
      { en: 'Mercury', phonetic: '/ˈmɜːkjəri/', zh: '水星', emoji: '☿', sentence: 'Mercury is small.', sentenceZh: '水星很小。' },
      { en: 'Uranus', phonetic: '/ˈjʊərənəs/', zh: '天王星', emoji: '🔵', sentence: 'Uranus is cold.', sentenceZh: '天王星很冷。' },
      { en: 'Cosmonaut', phonetic: '/ˈkɒsmənɔːt/', zh: '航天员', emoji: '🧑‍🚀', sentence: 'The cosmonaut is brave.', sentenceZh: '航天员很勇敢。' },
      { en: 'Astronomer', phonetic: '/əˈstrɒnəmər/', zh: '天文学家', emoji: '🔭', sentence: 'The astronomer studies stars.', sentenceZh: '天文学家研究星星。' },
      { en: 'Quasar', phonetic: '/ˈkweɪzɑːr/', zh: '类星体', emoji: '💫', sentence: 'The quasar is bright.', sentenceZh: '类星体很亮。' },
      { en: 'Pulsar', phonetic: '/ˈpʌlsɑːr/', zh: '脉冲星', emoji: '📡', sentence: 'The pulsar spins fast.', sentenceZh: '脉冲星转得很快。' }
    ]
  },
  {
    id: 'tableware', level: 'primary', name: '🍽️ 餐具', icon: '🍽️',
    items: [
      { en: 'Fork', phonetic: '/fɔːk/', zh: '叉子', emoji: '🍴', sentence: 'I eat with a fork.', sentenceZh: '我用叉子吃。' },
      { en: 'Spoon', phonetic: '/spuːn/', zh: '勺子', emoji: '🥄', sentence: 'I eat with a spoon.', sentenceZh: '我用勺子吃。' },
      { en: 'Knife', phonetic: '/naɪf/', zh: '刀', emoji: '🔪', sentence: 'I cut with a knife.', sentenceZh: '我用刀切。' },
      { en: 'Plate', phonetic: '/pleɪt/', zh: '盘子', emoji: '🍽️', sentence: 'The plate is round.', sentenceZh: '盘子是圆的。' },
      { en: 'Bowl', phonetic: '/bəʊl/', zh: '碗', emoji: '🥣', sentence: 'The bowl is deep.', sentenceZh: '碗很深。' },
      { en: 'Cup', phonetic: '/kʌp/', zh: '杯子', emoji: '☕', sentence: 'The cup is small.', sentenceZh: '杯子很小。' },
      { en: 'Glass', phonetic: '/ɡlɑːs/', zh: '玻璃杯', emoji: '🥃', sentence: 'The glass is clear.', sentenceZh: '玻璃杯是透明的。' },
      { en: 'Chopsticks', phonetic: '/ˈtʃɒpstɪks/', zh: '筷子', emoji: '🥢', sentence: 'I use chopsticks.', sentenceZh: '我用筷子。' },
      { en: 'Kettle', phonetic: '/ˈketl/', zh: '水壶', emoji: '🫖', sentence: 'The kettle is hot.', sentenceZh: '水壶很热。' },
      { en: 'Teapot', phonetic: '/ˈtiːpɒt/', zh: '茶壶', emoji: '🍵', sentence: 'The teapot is full.', sentenceZh: '茶壶是满的。' },
      { en: 'Napkin', phonetic: '/ˈnæpkɪn/', zh: '餐巾', emoji: '🧻', sentence: 'I wipe with a napkin.', sentenceZh: '我用餐巾擦。' },
      { en: 'Tray', phonetic: '/treɪ/', zh: '托盘', emoji: '🍽️', sentence: 'The tray is flat.', sentenceZh: '托盘是平的。' },
      { en: 'Pot', phonetic: '/pɒt/', zh: '锅', emoji: '🍲', sentence: 'The pot is big.', sentenceZh: '锅很大。' },
      { en: 'Pan', phonetic: '/pæn/', zh: '平底锅', emoji: '🍳', sentence: 'I cook with a pan.', sentenceZh: '我用平底锅做饭。' },
      { en: 'Straw', phonetic: '/strɔː/', zh: '吸管', emoji: '🥤', sentence: 'I drink with a straw.', sentenceZh: '我用吸管喝。' },
      { en: 'Mug', phonetic: '/mʌɡ/', zh: '马克杯', emoji: '☕', sentence: 'The mug is warm.', sentenceZh: '马克杯很暖。' },
      { en: 'Saucer', phonetic: '/ˈsɔːsər/', zh: '茶碟', emoji: '🍽️', sentence: 'The saucer is under the cup.', sentenceZh: '茶碟在杯子下面。' },
      { en: 'Jug', phonetic: '/dʒʌɡ/', zh: '大壶', emoji: '🫗', sentence: 'The jug holds water.', sentenceZh: '大壶装水。' },
      { en: 'Tongs', phonetic: '/tɒŋz/', zh: '夹子', emoji: '🥢', sentence: 'I pick up food with tongs.', sentenceZh: '我用夹子夹食物。' },
      { en: 'Spatula', phonetic: '/ˈspætʃələ/', zh: '锅铲', emoji: '🍳', sentence: 'I flip with a spatula.', sentenceZh: '我用锅铲翻面。' },
      { en: 'Grater', phonetic: '/ˈɡreɪtər/', zh: '擦丝器', emoji: '🧀', sentence: 'I grate cheese.', sentenceZh: '我用擦丝器擦奶酪。' },
      { en: 'Whisk', phonetic: '/wɪsk/', zh: '打蛋器', emoji: '🥚', sentence: 'I whisk the eggs.', sentenceZh: '我用打蛋器打蛋。' },
      { en: 'Ladle', phonetic: '/ˈleɪdl/', zh: '汤勺', emoji: '🥄', sentence: 'I serve soup with a ladle.', sentenceZh: '我用汤勺盛汤。' },
      { en: 'Colander', phonetic: '/ˈkʌləndər/', zh: '漏勺', emoji: '🍝', sentence: 'I drain with a colander.', sentenceZh: '我用漏勺沥水。' },
      { en: 'Cutting board', phonetic: '/ˈkʌtɪŋ bɔːd/', zh: '砧板', emoji: '🪵', sentence: 'I chop on a cutting board.', sentenceZh: '我在砧板上切菜。' },
      { en: 'Measuring cup', phonetic: '/ˈmeʒərɪŋ kʌp/', zh: '量杯', emoji: '🥛', sentence: 'I use a measuring cup.', sentenceZh: '我用量杯。' },
      { en: 'Toothpick', phonetic: '/ˈtuːθpɪk/', zh: '牙签', emoji: '🦷', sentence: 'I use a toothpick.', sentenceZh: '我用牙签。' },
      { en: 'Tablecloth', phonetic: '/ˈteɪblklɒθ/', zh: '桌布', emoji: '🍽️', sentence: 'The tablecloth is clean.', sentenceZh: '桌布很干净。' },
      { en: 'Flask', phonetic: '/flɑːsk/', zh: '保温瓶', emoji: '🧴', sentence: 'The flask keeps it warm.', sentenceZh: '保温瓶能保温。' },
      { en: 'Lid', phonetic: '/lɪd/', zh: '盖子', emoji: '🫙', sentence: 'The lid covers the pot.', sentenceZh: '盖子盖住锅。' }
    ]
  }
];

  // 插入到 phrases 主题之前，让词汇主题集中在前
  const idx = THEMES.findIndex(function (t) { return t.id === 'phrases'; });
  if (idx >= 0) THEMES.splice(idx, 0, ...newThemes);
  else THEMES.push(...newThemes);
})();
