// ============================================================
// 中学词汇库（level:'middle'）— 对标新课标中学英语词汇
// 复用 data2.js 的 IIFE 注入模式：插入到 phrases 主题之前
// ============================================================
(function () {
  const newThemes = [
    {
      id: 'ms-verbs', name: '🏃 中学核心动词', icon: '🏃', level: 'middle',
      items: [
        { en: 'achieve', phonetic: '/əˈtʃiːv/', zh: '实现，达成', emoji: '🏆', sentence: 'She achieved her dream.', sentenceZh: '她实现了梦想。' },
        { en: 'admit', phonetic: '/ədˈmɪt/', zh: '承认', emoji: '🙇', sentence: 'He admitted his mistake.', sentenceZh: '他承认了错误。' },
        { en: 'affect', phonetic: '/əˈfekt/', zh: '影响', emoji: '🔄', sentence: 'Rain affects the crops.', sentenceZh: '雨水影响庄稼。' },
        { en: 'agree', phonetic: '/əˈɡriː/', zh: '同意', emoji: '🤝', sentence: 'I agree with you.', sentenceZh: '我同意你。' },
        { en: 'allow', phonetic: '/əˈlaʊ/', zh: '允许', emoji: '✅', sentence: 'Smoking is not allowed.', sentenceZh: '不允许吸烟。' },
        { en: 'announce', phonetic: '/əˈnaʊns/', zh: '宣布', emoji: '📢', sentence: 'They announced the result.', sentenceZh: '他们宣布了结果。' },
        { en: 'appear', phonetic: '/əˈpɪər/', zh: '出现', emoji: '👁️', sentence: 'A star appeared.', sentenceZh: '一颗星出现了。' },
        { en: 'arrange', phonetic: '/əˈreɪndʒ/', zh: '安排', emoji: '📅', sentence: 'I arranged the meeting.', sentenceZh: '我安排了会议。' },
        { en: 'attend', phonetic: '/əˈtend/', zh: '出席', emoji: '🎫', sentence: 'She attended the wedding.', sentenceZh: '她出席了婚礼。' },
        { en: 'believe', phonetic: '/bɪˈliːv/', zh: '相信', emoji: '🙏', sentence: 'I believe you.', sentenceZh: '我相信你。' },
        { en: 'borrow', phonetic: '/ˈbɒrəʊ/', zh: '借', emoji: '💵', sentence: 'May I borrow your book?', sentenceZh: '我可以借你的书吗？' },
        { en: 'calculate', phonetic: '/ˈkælkjuleɪt/', zh: '计算', emoji: '🧮', sentence: 'He calculated the cost.', sentenceZh: '他计算了成本。' },
        { en: 'cancel', phonetic: '/ˈkænsl/', zh: '取消', emoji: '❌', sentence: 'They canceled the game.', sentenceZh: '他们取消了比赛。' },
        { en: 'celebrate', phonetic: '/ˈselɪbreɪt/', zh: '庆祝', emoji: '🎉', sentence: 'We celebrate the new year.', sentenceZh: '我们庆祝新年。' },
        { en: 'complain', phonetic: '/kəmˈpleɪn/', zh: '抱怨', emoji: '😤', sentence: 'Don\'t complain too much.', sentenceZh: '别抱怨太多。' },
        { en: 'complete', phonetic: '/kəmˈpliːt/', zh: '完成', emoji: '✓', sentence: 'I completed the task.', sentenceZh: '我完成了任务。' },
        { en: 'consider', phonetic: '/kənˈsɪdər/', zh: '考虑', emoji: '🤔', sentence: 'Please consider it.', sentenceZh: '请考虑一下。' },
        { en: 'continue', phonetic: '/kənˈtɪnjuː/', zh: '继续', emoji: '⏭️', sentence: 'Please continue reading.', sentenceZh: '请继续读。' },
        { en: 'create', phonetic: '/kriˈeɪt/', zh: '创造', emoji: '🎨', sentence: 'He created a new game.', sentenceZh: '他创造了一个新游戏。' },
        { en: 'decide', phonetic: '/dɪˈsaɪd/', zh: '决定', emoji: '🎯', sentence: 'She decided to go.', sentenceZh: '她决定去。' },
        { en: 'deliver', phonetic: '/dɪˈlɪvər/', zh: '递送', emoji: '📦', sentence: 'They deliver fast.', sentenceZh: '他们送得很快。' },
        { en: 'describe', phonetic: '/dɪˈskraɪb/', zh: '描述', emoji: '📝', sentence: 'Describe the picture.', sentenceZh: '描述这张图。' },
        { en: 'develop', phonetic: '/dɪˈveləp/', zh: '发展', emoji: '🌱', sentence: 'The city developed fast.', sentenceZh: '城市发展很快。' },
        { en: 'discover', phonetic: '/dɪˈskʌvər/', zh: '发现', emoji: '🔍', sentence: 'They discovered a cave.', sentenceZh: '他们发现了一个洞穴。' },
        { en: 'discuss', phonetic: '/dɪˈskʌs/', zh: '讨论', emoji: '💬', sentence: 'Let\'s discuss the plan.', sentenceZh: '我们讨论一下计划。' },
        { en: 'earn', phonetic: '/ɜːn/', zh: '赚取', emoji: '💰', sentence: 'She earns a lot.', sentenceZh: '她赚得很多。' },
        { en: 'encourage', phonetic: '/ɪnˈkʌrɪdʒ/', zh: '鼓励', emoji: '💪', sentence: 'My teacher encourages me.', sentenceZh: '老师鼓励我。' },
        { en: 'examine', phonetic: '/ɪɡˈzæmɪn/', zh: '检查', emoji: '🔬', sentence: 'The doctor examined him.', sentenceZh: '医生给他做了检查。' },
        { en: 'explain', phonetic: '/ɪkˈspleɪn/', zh: '解释', emoji: '📖', sentence: 'Can you explain it?', sentenceZh: '你能解释一下吗？' },
        { en: 'explore', phonetic: '/ɪkˈsplɔːr/', zh: '探索', emoji: '🧭', sentence: 'We explore the forest.', sentenceZh: '我们探索森林。' },
        { en: 'express', phonetic: '/ɪkˈspres/', zh: '表达', emoji: '🗣️', sentence: 'Express your idea.', sentenceZh: '表达你的想法。' },
        { en: 'improve', phonetic: '/ɪmˈpruːv/', zh: '改进', emoji: '📈', sentence: 'I want to improve my English.', sentenceZh: '我想提高英语。' },
        { en: 'include', phonetic: '/ɪnˈkluːd/', zh: '包含', emoji: '📦', sentence: 'The price includes tax.', sentenceZh: '价格包含税。' },
        { en: 'increase', phonetic: '/ɪnˈkriːs/', zh: '增加', emoji: '⬆️', sentence: 'Prices increased.', sentenceZh: '价格上涨了。' },
        { en: 'influence', phonetic: '/ˈɪnfluəns/', zh: '影响', emoji: '🌀', sentence: 'Music influences mood.', sentenceZh: '音乐影响情绪。' },
        { en: 'introduce', phonetic: '/ˌɪntrəˈdjuːs/', zh: '介绍', emoji: '👋', sentence: 'Let me introduce myself.', sentenceZh: '让我自我介绍。' },
        { en: 'organize', phonetic: '/ˈɔːɡənaɪz/', zh: '组织', emoji: '🗂️', sentence: 'She organized the files.', sentenceZh: '她整理了文件。' },
        { en: 'prepare', phonetic: '/prɪˈpeər/', zh: '准备', emoji: '🍳', sentence: 'I prepare dinner.', sentenceZh: '我准备晚餐。' },
        { en: 'prevent', phonetic: '/prɪˈvent/', zh: '阻止，预防', emoji: '🛡️', sentence: 'Wash hands to prevent illness.', sentenceZh: '洗手预防疾病。' },
        { en: 'produce', phonetic: '/prəˈdjuːs/', zh: '生产', emoji: '🏭', sentence: 'They produce cars.', sentenceZh: '他们生产汽车。' }
      ]
    },
    {
      id: 'ms-nouns-abstract', name: '💭 抽象名词', icon: '💭', level: 'middle',
      items: [
        { en: 'ability', phonetic: '/əˈbɪləti/', zh: '能力', emoji: '💪', sentence: 'He has the ability to lead.', sentenceZh: '他有领导能力。' },
        { en: 'adventure', phonetic: '/ədˈventʃər/', zh: '冒险', emoji: '🗺️', sentence: 'Life is an adventure.', sentenceZh: '生活是场冒险。' },
        { en: 'advice', phonetic: '/ədˈvaɪs/', zh: '建议', emoji: '💡', sentence: 'Thanks for your advice.', sentenceZh: '谢谢你的建议。' },
        { en: 'anger', phonetic: '/ˈæŋɡər/', zh: '愤怒', emoji: '😠', sentence: 'He spoke in anger.', sentenceZh: '他愤怒地说。' },
        { en: 'beauty', phonetic: '/ˈbjuːti/', zh: '美丽', emoji: '🌸', sentence: 'I love the beauty of nature.', sentenceZh: '我喜欢大自然的美。' },
        { en: 'belief', phonetic: '/bɪˈliːf/', zh: '信念', emoji: '🕊️', sentence: 'She has strong beliefs.', sentenceZh: '她有坚定的信念。' },
        { en: 'chance', phonetic: '/tʃɑːns/', zh: '机会', emoji: '🎲', sentence: 'Give me a chance.', sentenceZh: '给我一个机会。' },
        { en: 'character', phonetic: '/ˈkærəktər/', zh: '性格', emoji: '🎭', sentence: 'He has a good character.', sentenceZh: '他性格很好。' },
        { en: 'childhood', phonetic: '/ˈtʃaɪldhʊd/', zh: '童年', emoji: '🧒', sentence: 'My childhood was happy.', sentenceZh: '我的童年很快乐。' },
        { en: 'choice', phonetic: '/tʃɔɪs/', zh: '选择', emoji: '🤔', sentence: 'Make your choice.', sentenceZh: '做出你的选择。' },
        { en: 'courage', phonetic: '/ˈkʌrɪdʒ/', zh: '勇气', emoji: '🦁', sentence: 'She has courage.', sentenceZh: '她有勇气。' },
        { en: 'culture', phonetic: '/ˈkʌltʃər/', zh: '文化', emoji: '🏯', sentence: 'I love Chinese culture.', sentenceZh: '我喜欢中国文化。' },
        { en: 'danger', phonetic: '/ˈdeɪndʒər/', zh: '危险', emoji: '⚠️', sentence: 'Stay away from danger.', sentenceZh: '远离危险。' },
        { en: 'dream', phonetic: '/driːm/', zh: '梦想', emoji: '💭', sentence: 'Follow your dream.', sentenceZh: '追随你的梦想。' },
        { en: 'duty', phonetic: '/ˈdjuːti/', zh: '责任', emoji: '📋', sentence: 'It is my duty.', sentenceZh: '这是我的责任。' },
        { en: 'effort', phonetic: '/ˈefət/', zh: '努力', emoji: '💦', sentence: 'His effort paid off.', sentenceZh: '他的努力有了回报。' },
        { en: 'emotion', phonetic: '/ɪˈməʊʃn/', zh: '情感', emoji: '❤️', sentence: 'Music shows emotion.', sentenceZh: '音乐表达情感。' },
        { en: 'energy', phonetic: '/ˈenədʒi/', zh: '能量', emoji: '⚡', sentence: 'Kids have lots of energy.', sentenceZh: '孩子们精力充沛。' },
        { en: 'experience', phonetic: '/ɪkˈspɪəriəns/', zh: '经验', emoji: '📚', sentence: 'He has much experience.', sentenceZh: '他很有经验。' },
        { en: 'failure', phonetic: '/ˈfeɪljər/', zh: '失败', emoji: '📉', sentence: 'Failure is the mother of success.', sentenceZh: '失败是成功之母。' },
        { en: 'faith', phonetic: '/feɪθ/', zh: '信仰', emoji: '🛐', sentence: 'Keep your faith.', sentenceZh: '保持你的信仰。' },
        { en: 'freedom', phonetic: '/ˈfriːdəm/', zh: '自由', emoji: '🦅', sentence: 'We love freedom.', sentenceZh: '我们热爱自由。' },
        { en: 'friendship', phonetic: '/ˈfrendʃɪp/', zh: '友谊', emoji: '👭', sentence: 'Friendship is important.', sentenceZh: '友谊很重要。' },
        { en: 'future', phonetic: '/ˈfjuːtʃər/', zh: '未来', emoji: '🚀', sentence: 'Think about the future.', sentenceZh: '想想未来。' },
        { en: 'happiness', phonetic: '/ˈhæpinəs/', zh: '幸福', emoji: '😊', sentence: 'Health brings happiness.', sentenceZh: '健康带来幸福。' },
        { en: 'honesty', phonetic: '/ˈɒnəsti/', zh: '诚实', emoji: '🤍', sentence: 'Honesty is the best policy.', sentenceZh: '诚实为上策。' },
        { en: 'hope', phonetic: '/həʊp/', zh: '希望', emoji: '🌟', sentence: 'Don\'t lose hope.', sentenceZh: '不要失去希望。' },
        { en: 'idea', phonetic: '/aɪˈdɪə/', zh: '想法', emoji: '💡', sentence: 'Good idea!', sentenceZh: '好主意！' },
        { en: 'imagination', phonetic: '/ɪˌmædʒɪˈneɪʃn/', zh: '想象', emoji: '🎆', sentence: 'Use your imagination.', sentenceZh: '发挥你的想象。' },
        { en: 'independence', phonetic: '/ˌɪndɪˈpendəns/', zh: '独立', emoji: '🆓', sentence: 'They value independence.', sentenceZh: '他们重视独立。' },
        { en: 'intelligence', phonetic: '/ɪnˈtelɪdʒəns/', zh: '智力', emoji: '🧠', sentence: 'He shows great intelligence.', sentenceZh: '他展现出很高的智力。' },
        { en: 'joy', phonetic: '/dʒɔɪ/', zh: '快乐', emoji: '😄', sentence: 'The joy of learning.', sentenceZh: '学习的快乐。' },
        { en: 'justice', phonetic: '/ˈdʒʌstɪs/', zh: '正义', emoji: '⚖️', sentence: 'We believe in justice.', sentenceZh: '我们相信正义。' },
        { en: 'knowledge', phonetic: '/ˈnɒlɪdʒ/', zh: '知识', emoji: '📖', sentence: 'Knowledge is power.', sentenceZh: '知识就是力量。' },
        { en: 'memory', phonetic: '/ˈmeməri/', zh: '记忆', emoji: '🧩', sentence: 'I have a good memory.', sentenceZh: '我记性好。' },
        { en: 'patience', phonetic: '/ˈpeɪʃns/', zh: '耐心', emoji: '⏳', sentence: 'Teaching needs patience.', sentenceZh: '教学需要耐心。' },
        { en: 'peace', phonetic: '/piːs/', zh: '和平', emoji: '🕊️', sentence: 'We wish for peace.', sentenceZh: '我们祈愿和平。' },
        { en: 'purpose', phonetic: '/ˈpɜːpəs/', zh: '目的', emoji: '🎯', sentence: 'What is your purpose?', sentenceZh: '你的目的是什么？' },
        { en: 'success', phonetic: '/səkˈses/', zh: '成功', emoji: '🏆', sentence: 'Hard work leads to success.', sentenceZh: '努力带来成功。' },
        { en: 'truth', phonetic: '/truːθ/', zh: '真相', emoji: '🔎', sentence: 'Tell the truth.', sentenceZh: '说实话。' },
        { en: 'wisdom', phonetic: '/ˈwɪzdəm/', zh: '智慧', emoji: '🦉', sentence: 'Wisdom comes with age.', sentenceZh: '智慧随年龄增长。' }
      ]
    },
    {
      id: 'ms-subjects', name: '📚 学科科目', icon: '📚', level: 'middle',
      items: [
        { en: 'math', phonetic: '/mæθ/', zh: '数学', emoji: '🔢', sentence: 'Math is my favorite.', sentenceZh: '数学是我最喜欢的。' },
        { en: 'Chinese', phonetic: '/ˌtʃaɪˈniːz/', zh: '语文', emoji: '🀄', sentence: 'I study Chinese.', sentenceZh: '我学语文。' },
        { en: 'English', phonetic: '/ˈɪŋɡlɪʃ/', zh: '英语', emoji: '🇬🇧', sentence: 'English is fun.', sentenceZh: '英语很有趣。' },
        { en: 'history', phonetic: '/ˈhɪstri/', zh: '历史', emoji: '🏛️', sentence: 'History tells the past.', sentenceZh: '历史讲述过去。' },
        { en: 'geography', phonetic: '/dʒiˈɒɡrəfi/', zh: '地理', emoji: '🌍', sentence: 'Geography is about the earth.', sentenceZh: '地理是关于地球的。' },
        { en: 'biology', phonetic: '/baɪˈɒlədʒi/', zh: '生物', emoji: '🧬', sentence: 'Biology studies life.', sentenceZh: '生物研究生命。' },
        { en: 'chemistry', phonetic: '/ˈkemɪstri/', zh: '化学', emoji: '⚗️', sentence: 'Chemistry is exciting.', sentenceZh: '化学很奇妙。' },
        { en: 'physics', phonetic: '/ˈfɪzɪks/', zh: '物理', emoji: '🔭', sentence: 'Physics explains the world.', sentenceZh: '物理解释世界。' },
        { en: 'politics', phonetic: '/ˈpɒlətɪks/', zh: '政治', emoji: '🏛️', sentence: 'Politics is complex.', sentenceZh: '政治很复杂。' },
        { en: 'art', phonetic: '/ɑːt/', zh: '美术', emoji: '🎨', sentence: 'I love art class.', sentenceZh: '我喜欢美术课。' },
        { en: 'music', phonetic: '/ˈmjuːzɪk/', zh: '音乐', emoji: '🎵', sentence: 'Music makes me happy.', sentenceZh: '音乐让我快乐。' },
        { en: 'PE', phonetic: '/ˌpiː ˈiː/', zh: '体育', emoji: '⚽', sentence: 'PE is on Monday.', sentenceZh: '体育课在周一。' },
        { en: 'computer', phonetic: '/kəmˈpjuːtər/', zh: '电脑', emoji: '💻', sentence: 'We learn computer skills.', sentenceZh: '我们学电脑技能。' },
        { en: 'science', phonetic: '/ˈsaɪəns/', zh: '科学', emoji: '🔬', sentence: 'Science is amazing.', sentenceZh: '科学很神奇。' },
        { en: 'literature', phonetic: '/ˈlɪtrətʃər/', zh: '文学', emoji: '📜', sentence: 'I enjoy literature.', sentenceZh: '我喜爱文学。' },
        { en: 'algebra', phonetic: '/ˈældʒɪbrə/', zh: '代数', emoji: '➗', sentence: 'Algebra is hard.', sentenceZh: '代数很难。' },
        { en: 'geometry', phonetic: '/dʒiˈɒmətri/', zh: '几何', emoji: '📐', sentence: 'Geometry uses shapes.', sentenceZh: '几何用图形。' },
        { en: 'astronomy', phonetic: '/əˈstrɒnəmi/', zh: '天文学', emoji: '🪐', sentence: 'Astronomy studies stars.', sentenceZh: '天文学研究星星。' },
        { en: 'philosophy', phonetic: '/fəˈlɒsəfi/', zh: '哲学', emoji: '🧐', sentence: 'Philosophy asks big questions.', sentenceZh: '哲学问大问题。' },
        { en: 'psychology', phonetic: '/saɪˈkɒlədʒi/', zh: '心理学', emoji: '🧠', sentence: 'Psychology studies the mind.', sentenceZh: '心理学研究心理。' },
        { en: 'sociology', phonetic: '/ˌsəʊsiˈɒlədʒi/', zh: '社会学', emoji: '👥', sentence: 'Sociology studies society.', sentenceZh: '社会学研究社会。' },
        { en: 'economics', phonetic: '/ˌiːkəˈnɒmɪks/', zh: '经济学', emoji: '💹', sentence: 'Economics is about money.', sentenceZh: '经济学关于钱。' },
        { en: 'law', phonetic: '/lɔː/', zh: '法律', emoji: '⚖️', sentence: 'Law keeps order.', sentenceZh: '法律维持秩序。' },
        { en: 'medicine', phonetic: '/ˈmedsn/', zh: '医学', emoji: '💊', sentence: 'He studies medicine.', sentenceZh: '他学医。' },
        { en: 'engineering', phonetic: '/ˌendʒɪˈnɪərɪŋ/', zh: '工程', emoji: '🔧', sentence: 'Engineering builds things.', sentenceZh: '工程建造东西。' },
        { en: 'language', phonetic: '/ˈlæŋɡwɪdʒ/', zh: '语言', emoji: '💬', sentence: 'Language connects people.', sentenceZh: '语言连接人们。' },
        { en: 'grammar', phonetic: '/ˈɡræmər/', zh: '语法', emoji: '✍️', sentence: 'Grammar is important.', sentenceZh: '语法很重要。' },
        { en: 'vocabulary', phonetic: '/vəˈkæbjələri/', zh: '词汇', emoji: '🔤', sentence: 'Learn new vocabulary.', sentenceZh: '学新词汇。' }
      ]
    },
    {
      id: 'ms-society', name: '🏛️ 社会生活', icon: '🏛️', level: 'middle',
      items: [
        { en: 'community', phonetic: '/kəˈmjuːnəti/', zh: '社区', emoji: '🏘️', sentence: 'Our community is friendly.', sentenceZh: '我们的社区很友好。' },
        { en: 'society', phonetic: '/səˈsaɪəti/', zh: '社会', emoji: '🌐', sentence: 'Society is changing.', sentenceZh: '社会在变化。' },
        { en: 'government', phonetic: '/ˈɡʌvənmənt/', zh: '政府', emoji: '🏛️', sentence: 'The government helps people.', sentenceZh: '政府帮助人民。' },
        { en: 'citizen', phonetic: '/ˈsɪtɪzn/', zh: '公民', emoji: '🧑', sentence: 'Be a good citizen.', sentenceZh: '做个好公民。' },
        { en: 'tradition', phonetic: '/trəˈdɪʃn/', zh: '传统', emoji: '🎎', sentence: 'We keep our traditions.', sentenceZh: '我们保留传统。' },
        { en: 'festival', phonetic: '/ˈfestɪvl/', zh: '节日', emoji: '🎊', sentence: 'Spring festival is coming.', sentenceZh: '春节快到了。' },
        { en: 'holiday', phonetic: '/ˈhɒlədeɪ/', zh: '假期', emoji: '🏖️', sentence: 'We travel on holiday.', sentenceZh: '假期我们去旅行。' },
        { en: 'ceremony', phonetic: '/ˈserəməni/', zh: '仪式', emoji: '🎊', sentence: 'The ceremony was grand.', sentenceZh: '仪式很隆重。' },
        { en: 'marriage', phonetic: '/ˈmærɪdʒ/', zh: '婚姻', emoji: '💍', sentence: 'Marriage needs love.', sentenceZh: '婚姻需要爱。' },
        { en: 'election', phonetic: '/ɪˈlekʃn/', zh: '选举', emoji: '🗳️', sentence: 'The election is fair.', sentenceZh: '选举很公平。' },
        { en: 'leader', phonetic: '/ˈliːdər/', zh: '领导', emoji: '👑', sentence: 'A good leader listens.', sentenceZh: '好领导善听。' },
        { en: 'president', phonetic: '/ˈprezɪdənt/', zh: '总统', emoji: '👔', sentence: 'The president spoke.', sentenceZh: '总统发言了。' },
        { en: 'rule', phonetic: '/ruːl/', zh: '规则', emoji: '📏', sentence: 'Follow the rules.', sentenceZh: '遵守规则。' },
        { en: 'right', phonetic: '/raɪt/', zh: '权利', emoji: '✊', sentence: 'We have rights.', sentenceZh: '我们有权利。' },
        { en: 'tax', phonetic: '/tæks/', zh: '税', emoji: '💸', sentence: 'We pay tax.', sentenceZh: '我们交税。' },
        { en: 'policy', phonetic: '/ˈpɒləsi/', zh: '政策', emoji: '📋', sentence: 'The policy changed.', sentenceZh: '政策变了。' },
        { en: 'public', phonetic: '/ˈpʌblɪk/', zh: '公共', emoji: '👨‍👩‍👧‍👦', sentence: 'Keep the public place clean.', sentenceZh: '保持公共场所清洁。' },
        { en: 'private', phonetic: '/ˈpraɪvət/', zh: '私人', emoji: '🔒', sentence: 'This is private.', sentenceZh: '这是私人的。' },
        { en: 'official', phonetic: '/əˈfɪʃl/', zh: '官员', emoji: '🎖️', sentence: 'The official visited.', sentenceZh: '官员来访。' },
        { en: 'police', phonetic: '/pəˈliːs/', zh: '警察', emoji: '👮', sentence: 'Call the police.', sentenceZh: '报警。' },
        { en: 'army', phonetic: '/ˈɑːmi/', zh: '军队', emoji: '🪖', sentence: 'The army protects us.', sentenceZh: '军队保护我们。' },
        { en: 'war', phonetic: '/wɔːr/', zh: '战争', emoji: '⚔️', sentence: 'War is terrible.', sentenceZh: '战争很可怕。' },
        { en: 'peace', phonetic: '/piːs/', zh: '和平', emoji: '🕊️', sentence: 'We want peace.', sentenceZh: '我们要和平。' },
        { en: 'voting', phonetic: '/ˈvəʊtɪŋ/', zh: '投票', emoji: '🗳️', sentence: 'Voting is a duty.', sentenceZh: '投票是义务。' },
        { en: 'charity', phonetic: '/ˈtʃærəti/', zh: '慈善', emoji: '🤲', sentence: 'She works for charity.', sentenceZh: '她做慈善。' },
        { en: 'volunteer', phonetic: '/ˌvɒlənˈtɪər/', zh: '志愿者', emoji: '🙌', sentence: 'He is a volunteer.', sentenceZh: '他是志愿者。' },
        { en: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', zh: '环境', emoji: '🌳', sentence: 'Protect the environment.', sentenceZh: '保护环境。' },
        { en: 'culture', phonetic: '/ˈkʌltʃər/', zh: '文化', emoji: '🎎', sentence: 'Culture is rich here.', sentenceZh: '这里文化丰富。' },
        { en: 'generation', phonetic: '/ˌdʒenəˈreɪʃn/', zh: '世代', emoji: '👪', sentence: 'A new generation comes.', sentenceZh: '新一代来了。' },
        { en: 'population', phonetic: '/ˌpɒpjuˈleɪʃn/', zh: '人口', emoji: '👪', sentence: 'The population grows.', sentenceZh: '人口在增长。' },
        { en: 'nation', phonetic: '/ˈneɪʃn/', zh: '国家', emoji: '🏳️', sentence: 'Our nation is strong.', sentenceZh: '我们的国家很强。' },
        { en: 'freedom', phonetic: '/ˈfriːdəm/', zh: '自由', emoji: '🦅', sentence: 'Freedom is precious.', sentenceZh: '自由很珍贵。' }
      ]
    },
    {
      id: 'ms-technology', name: '💻 科技', icon: '💻', level: 'middle',
      items: [
        { en: 'computer', phonetic: '/kəmˈpjuːtər/', zh: '电脑', emoji: '💻', sentence: 'I use a computer.', sentenceZh: '我用电脑。' },
        { en: 'internet', phonetic: '/ˈɪntənet/', zh: '互联网', emoji: '🌐', sentence: 'The internet is useful.', sentenceZh: '互联网很有用。' },
        { en: 'website', phonetic: '/ˈwebsaɪt/', zh: '网站', emoji: '📄', sentence: 'Visit our website.', sentenceZh: '访问我们的网站。' },
        { en: 'software', phonetic: '/ˈsɒftweər/', zh: '软件', emoji: '💿', sentence: 'Install the software.', sentenceZh: '安装软件。' },
        { en: 'hardware', phonetic: '/ˈhɑːdweər/', zh: '硬件', emoji: '🔩', sentence: 'Hardware is the machine.', sentenceZh: '硬件是机器。' },
        { en: 'network', phonetic: '/ˈnetwɜːk/', zh: '网络', emoji: '🕸️', sentence: 'The network is fast.', sentenceZh: '网络很快。' },
        { en: 'database', phonetic: '/ˈdeɪtəbeɪs/', zh: '数据库', emoji: '🗄️', sentence: 'Store data in a database.', sentenceZh: '数据存到数据库。' },
        { en: 'program', phonetic: '/ˈprəʊɡræm/', zh: '程序', emoji: '📟', sentence: 'Write a program.', sentenceZh: '写程序。' },
        { en: 'programmer', phonetic: '/ˈprəʊɡræmər/', zh: '程序员', emoji: '🧑‍💻', sentence: 'She is a programmer.', sentenceZh: '她是程序员。' },
        { en: 'keyboard', phonetic: '/ˈkiːbɔːd/', zh: '键盘', emoji: '⌨️', sentence: 'Type on the keyboard.', sentenceZh: '在键盘上打字。' },
        { en: 'mouse', phonetic: '/maʊs/', zh: '鼠标', emoji: '🖱️', sentence: 'Click the mouse.', sentenceZh: '点鼠标。' },
        { en: 'screen', phonetic: '/skriːn/', zh: '屏幕', emoji: '🖥️', sentence: 'Look at the screen.', sentenceZh: '看屏幕。' },
        { en: 'monitor', phonetic: '/ˈmɒnɪtər/', zh: '显示器', emoji: '🖥️', sentence: 'The monitor is bright.', sentenceZh: '显示器很亮。' },
        { en: 'printer', phonetic: '/ˈprɪntər/', zh: '打印机', emoji: '🖨️', sentence: 'Use the printer.', sentenceZh: '用打印机。' },
        { en: 'camera', phonetic: '/ˈkæmərə/', zh: '相机', emoji: '📷', sentence: 'Take a camera.', sentenceZh: '带上相机。' },
        { en: 'smartphone', phonetic: '/ˈsmɑːtfəʊn/', zh: '智能手机', emoji: '📱', sentence: 'I have a smartphone.', sentenceZh: '我有智能手机。' },
        { en: 'tablet', phonetic: '/ˈtæblət/', zh: '平板电脑', emoji: '📲', sentence: 'She uses a tablet.', sentenceZh: '她用平板。' },
        { en: 'laptop', phonetic: '/ˈlæptɒp/', zh: '笔记本电脑', emoji: '💻', sentence: 'My laptop is light.', sentenceZh: '我的笔记本很轻。' },
        { en: 'robot', phonetic: '/ˈrəʊbɒt/', zh: '机器人', emoji: '🤖', sentence: 'The robot helps us.', sentenceZh: '机器人帮助我们。' },
        { en: 'algorithm', phonetic: '/ˈælɡərɪðəm/', zh: '算法', emoji: '🧮', sentence: 'An algorithm solves problems.', sentenceZh: '算法解决问题。' },
        { en: 'digital', phonetic: '/ˈdɪdʒɪtl/', zh: '数字的', emoji: '🔢', sentence: 'We live in a digital age.', sentenceZh: '我们生活在数字时代。' },
        { en: 'electronic', phonetic: '/ɪˌlekˈtrɒnɪk/', zh: '电子的', emoji: '🔌', sentence: 'Electronic devices are common.', sentenceZh: '电子设备很常见。' },
        { en: 'device', phonetic: '/dɪˈvaɪs/', zh: '设备', emoji: '📟', sentence: 'This device is new.', sentenceZh: '这设备是新的。' },
        { en: 'engine', phonetic: '/ˈendʒɪn/', zh: '引擎', emoji: '⚙️', sentence: 'The engine is powerful.', sentenceZh: '引擎很强劲。' },
        { en: 'battery', phonetic: '/ˈbætri/', zh: '电池', emoji: '🔋', sentence: 'Charge the battery.', sentenceZh: '给电池充电。' },
        { en: 'satellite', phonetic: '/ˈsætəlaɪt/', zh: '卫星', emoji: '🛰️', sentence: 'A satellite orbits earth.', sentenceZh: '卫星绕地球转。' },
        { en: 'rocket', phonetic: '/ˈrɒkɪt/', zh: '火箭', emoji: '🚀', sentence: 'The rocket launched.', sentenceZh: '火箭发射了。' },
        { en: 'planet', phonetic: '/ˈplænɪt/', zh: '行星', emoji: '🪐', sentence: 'Mars is a planet.', sentenceZh: '火星是行星。' },
        { en: 'galaxy', phonetic: '/ˈɡæləksi/', zh: '星系', emoji: '🌌', sentence: 'The galaxy is huge.', sentenceZh: '星系很大。' },
        { en: 'astronaut', phonetic: '/ˈæstrənɔːt/', zh: '宇航员', emoji: '👨‍🚀', sentence: 'The astronaut is brave.', sentenceZh: '宇航员很勇敢。' },
        { en: 'telescope', phonetic: '/ˈtelɪskəʊp/', zh: '望远镜', emoji: '🔭', sentence: 'Look through a telescope.', sentenceZh: '用望远镜看。' },
        { en: 'microscope', phonetic: '/ˈmaɪkrəskəʊp/', zh: '显微镜', emoji: '🔬', sentence: 'Use a microscope.', sentenceZh: '用显微镜。' },
        { en: 'experiment', phonetic: '/ɪkˈsperɪmənt/', zh: '实验', emoji: '🧪', sentence: 'Do the experiment.', sentenceZh: '做实验。' },
        { en: 'invention', phonetic: '/ɪnˈvenʃn/', zh: '发明', emoji: '💡', sentence: 'The invention changed the world.', sentenceZh: '这发明改变了世界。' },
        { en: 'discovery', phonetic: '/dɪˈskʌvəri/', zh: '发现', emoji: '🔍', sentence: 'It was a great discovery.', sentenceZh: '这是个伟大的发现。' },
        { en: 'machine', phonetic: '/məˈʃiːn/', zh: '机器', emoji: '⚙️', sentence: 'The machine works well.', sentenceZh: '机器运转良好。' },
        { en: 'system', phonetic: '/ˈsɪstəm/', zh: '系统', emoji: '🗂️', sentence: 'The system is fast.', sentenceZh: '系统很快。' },
        { en: 'code', phonetic: '/kəʊd/', zh: '代码', emoji: '💻', sentence: 'Write clean code.', sentenceZh: '写干净的代码。' }
      ]
    },
    {
      id: 'ms-emotions-adv', name: '🎭 情感进阶', icon: '🎭', level: 'middle',
      items: [
        { en: 'anxious', phonetic: '/ˈæŋkʃəs/', zh: '焦虑的', emoji: '😰', sentence: 'She felt anxious.', sentenceZh: '她感到焦虑。' },
        { en: 'depressed', phonetic: '/dɪˈprest/', zh: '沮丧的', emoji: '😔', sentence: 'He looked depressed.', sentenceZh: '他看起来很沮丧。' },
        { en: 'delighted', phonetic: '/dɪˈlaɪtɪd/', zh: '高兴的', emoji: '🥰', sentence: 'I am delighted.', sentenceZh: '我很高兴。' },
        { en: 'disgusted', phonetic: '/dɪsˈɡʌstɪd/', zh: '厌恶的', emoji: '🤢', sentence: 'She was disgusted.', sentenceZh: '她感到厌恶。' },
        { en: 'confused', phonetic: '/kənˈfjuːzd/', zh: '困惑的', emoji: '😕', sentence: 'I am confused.', sentenceZh: '我困惑了。' },
        { en: 'embarrassed', phonetic: '/ɪmˈbærəst/', zh: '尴尬的', emoji: '😳', sentence: 'He felt embarrassed.', sentenceZh: '他感到尴尬。' },
        { en: 'frustrated', phonetic: '/frʌˈstreɪtɪd/', zh: '挫败的', emoji: '😣', sentence: 'She was frustrated.', sentenceZh: '她感到挫败。' },
        { en: 'guilty', phonetic: '/ˈɡɪlti/', zh: '内疚的', emoji: '😖', sentence: 'I feel guilty.', sentenceZh: '我感到内疚。' },
        { en: 'jealous', phonetic: '/ˈdʒeləs/', zh: '嫉妒的', emoji: '😒', sentence: 'He is jealous.', sentenceZh: '他嫉妒了。' },
        { en: 'lonely', phonetic: '/ˈləʊnli/', zh: '孤独的', emoji: '🥺', sentence: 'She feels lonely.', sentenceZh: '她感到孤独。' },
        { en: 'proud', phonetic: '/praʊd/', zh: '骄傲的', emoji: '😤', sentence: 'I am proud of you.', sentenceZh: '我为你骄傲。' },
        { en: 'relieved', phonetic: '/rɪˈliːvd/', zh: '宽慰的', emoji: '😮‍💨', sentence: 'She felt relieved.', sentenceZh: '她松了口气。' },
        { en: 'ashamed', phonetic: '/əˈʃeɪmd/', zh: '羞愧的', emoji: '🫣', sentence: 'He was ashamed.', sentenceZh: '他感到羞愧。' },
        { en: 'sympathetic', phonetic: '/ˌsɪmpəˈθetɪk/', zh: '同情的', emoji: '🤗', sentence: 'Be sympathetic.', sentenceZh: '要有同情心。' },
        { en: 'terrified', phonetic: '/ˈterɪfaɪd/', zh: '极度害怕的', emoji: '😱', sentence: 'She was terrified.', sentenceZh: '她吓坏了。' },
        { en: 'thrilled', phonetic: '/θrɪld/', zh: '激动的', emoji: '🤩', sentence: 'I am thrilled!', sentenceZh: '我太激动了！' },
        { en: 'disappointed', phonetic: '/ˌdɪsəˈpɔɪntɪd/', zh: '失望的', emoji: '😞', sentence: 'He was disappointed.', sentenceZh: '他很失望。' },
        { en: 'content', phonetic: '/kənˈtent/', zh: '满足的', emoji: '😌', sentence: 'She feels content.', sentenceZh: '她很满足。' },
        { en: 'grateful', phonetic: '/ˈɡreɪtfl/', zh: '感激的', emoji: '🙏', sentence: 'I am grateful.', sentenceZh: '我很感激。' },
        { en: 'hopeful', phonetic: '/ˈhəʊpfl/', zh: '充满希望的', emoji: '🌟', sentence: 'Stay hopeful.', sentenceZh: '保持希望。' },
        { en: 'optimistic', phonetic: '/ˌɒptɪˈmɪstɪk/', zh: '乐观的', emoji: '🙂', sentence: 'He is optimistic.', sentenceZh: '他很乐观。' },
        { en: 'pessimistic', phonetic: '/ˌpesɪˈmɪstɪk/', zh: '悲观的', emoji: '☹️', sentence: 'Don\'t be pessimistic.', sentenceZh: '别悲观。' },
        { en: 'calm', phonetic: '/kɑːm/', zh: '平静的', emoji: '🧘', sentence: 'Keep calm.', sentenceZh: '保持冷静。' },
        { en: 'nervous', phonetic: '/ˈnɜːvəs/', zh: '紧张的', emoji: '😟', sentence: 'She is nervous.', sentenceZh: '她很紧张。' },
        { en: 'shocked', phonetic: '/ʃɒkt/', zh: '震惊的', emoji: '😲', sentence: 'I was shocked.', sentenceZh: '我很震惊。' },
        { en: 'miserable', phonetic: '/ˈmɪzrəbl/', zh: '痛苦的', emoji: '😢', sentence: 'He felt miserable.', sentenceZh: '他感到痛苦。' },
        { en: 'enthusiastic', phonetic: '/ɪnˌθjuːziˈæstɪk/', zh: '热情的', emoji: '🔥', sentence: 'She is enthusiastic.', sentenceZh: '她很热情。' },
        { en: 'bored', phonetic: '/bɔːd/', zh: '无聊的', emoji: '🥱', sentence: 'The kids are bored.', sentenceZh: '孩子们无聊了。' },
        { en: 'stubborn', phonetic: '/ˈstʌbən/', zh: '固执的', emoji: '😾', sentence: 'He is stubborn.', sentenceZh: '他很固执。' },
        { en: 'sensitive', phonetic: '/ˈsensətɪv/', zh: '敏感的', emoji: '🌸', sentence: 'She is sensitive.', sentenceZh: '她很敏感。' },
        { en: 'confident', phonetic: '/ˈkɒnfɪdənt/', zh: '自信的', emoji: '😎', sentence: 'Be confident!', sentenceZh: '要自信！' },
        { en: 'curious', phonetic: '/ˈkjʊəriəs/', zh: '好奇的', emoji: '🤓', sentence: 'Kids are curious.', sentenceZh: '孩子很好奇。' }
      ]
    },
    {
      id: 'ms-adjectives', name: '🎨 描述形容词', icon: '🎨', level: 'middle',
      items: [
        { en: 'beautiful', phonetic: '/ˈbjuːtɪfl/', zh: '美丽的', emoji: '🌹', sentence: 'She is beautiful.', sentenceZh: '她很美。' },
        { en: 'ugly', phonetic: '/ˈʌɡli/', zh: '丑陋的', emoji: '🥴', sentence: 'The bug is ugly.', sentenceZh: '这虫子很丑。' },
        { en: 'gorgeous', phonetic: '/ˈɡɔːdʒəs/', zh: '极美的', emoji: '💅', sentence: 'The dress is gorgeous.', sentenceZh: '裙子极美。' },
        { en: 'handsome', phonetic: '/ˈhænsəm/', zh: '英俊的', emoji: '🤴', sentence: 'He is handsome.', sentenceZh: '他很帅。' },
        { en: 'attractive', phonetic: '/əˈtræktɪv/', zh: '吸引人的', emoji: '✨', sentence: 'The idea is attractive.', sentenceZh: '这想法很吸引人。' },
        { en: 'comfortable', phonetic: '/ˈkʌmftəbl/', zh: '舒适的', emoji: '🛋️', sentence: 'The bed is comfortable.', sentenceZh: '床很舒服。' },
        { en: 'convenient', phonetic: '/kənˈviːniənt/', zh: '方便的', emoji: '🛒', sentence: 'It is convenient.', sentenceZh: '很方便。' },
        { en: 'delicious', phonetic: '/dɪˈlɪʃəs/', zh: '美味的', emoji: '😋', sentence: 'The food is delicious.', sentenceZh: '食物很美味。' },
        { en: 'disgusting', phonetic: '/dɪsˈɡʌstɪŋ/', zh: '恶心的', emoji: '🤮', sentence: 'The smell is disgusting.', sentenceZh: '气味很恶心。' },
        { en: 'expensive', phonetic: '/ɪkˈspensɪv/', zh: '昂贵的', emoji: '💎', sentence: 'It is expensive.', sentenceZh: '很贵。' },
        { en: 'cheap', phonetic: '/tʃiːp/', zh: '便宜的', emoji: '🏷️', sentence: 'The shirt is cheap.', sentenceZh: '衬衫很便宜。' },
        { en: 'enormous', phonetic: '/ɪˈnɔːməs/', zh: '巨大的', emoji: '🐘', sentence: 'The elephant is enormous.', sentenceZh: '大象巨大。' },
        { en: 'tiny', phonetic: '/ˈtaɪni/', zh: '微小的', emoji: '🐜', sentence: 'The ant is tiny.', sentenceZh: '蚂蚁很小。' },
        { en: 'ancient', phonetic: '/ˈeɪnʃənt/', zh: '古老的', emoji: '🏛️', sentence: 'It is an ancient city.', sentenceZh: '这是座古城。' },
        { en: 'modern', phonetic: '/ˈmɒdn/', zh: '现代的', emoji: '🏙️', sentence: 'The building is modern.', sentenceZh: '这楼很现代。' },
        { en: 'boring', phonetic: '/ˈbɔːrɪŋ/', zh: '无聊的', emoji: '🥱', sentence: 'The film is boring.', sentenceZh: '电影很无聊。' },
        { en: 'exciting', phonetic: '/ɪkˈsaɪtɪŋ/', zh: '令人兴奋的', emoji: '🎉', sentence: 'The game is exciting.', sentenceZh: '比赛很刺激。' },
        { en: 'relaxing', phonetic: '/rɪˈlæksɪŋ/', zh: '令人放松的', emoji: '🛀', sentence: 'Music is relaxing.', sentenceZh: '音乐令人放松。' },
        { en: 'exhausting', phonetic: '/ɪɡˈzɔːstɪŋ/', zh: '令人筋疲力尽的', emoji: '😵', sentence: 'The run was exhausting.', sentenceZh: '跑步很累人。' },
        { en: 'difficult', phonetic: '/ˈdɪfɪkəlt/', zh: '困难的', emoji: '🧗', sentence: 'The test is difficult.', sentenceZh: '考试很难。' },
        { en: 'easy', phonetic: '/ˈiːzi/', zh: '容易的', emoji: '😊', sentence: 'It is easy.', sentenceZh: '很简单。' },
        { en: 'impossible', phonetic: '/ɪmˈpɒsəbl/', zh: '不可能的', emoji: '🚫', sentence: 'It is impossible.', sentenceZh: '不可能。' },
        { en: 'possible', phonetic: '/ˈpɒsəbl/', zh: '可能的', emoji: '✅', sentence: 'It is possible.', sentenceZh: '有可能。' },
        { en: 'necessary', phonetic: '/ˈnesəsəri/', zh: '必要的', emoji: '📌', sentence: 'Water is necessary.', sentenceZh: '水是必需的。' },
        { en: 'important', phonetic: '/ɪmˈpɔːtnt/', zh: '重要的', emoji: '❗', sentence: 'Family is important.', sentenceZh: '家庭很重要。' },
        { en: 'similar', phonetic: '/ˈsɪmələr/', zh: '相似的', emoji: '👯', sentence: 'They are similar.', sentenceZh: '他们很相似。' },
        { en: 'different', phonetic: '/ˈdɪfrənt/', zh: '不同的', emoji: '🔀', sentence: 'We are different.', sentenceZh: '我们不同。' },
        { en: 'familiar', phonetic: '/fəˈmɪliər/', zh: '熟悉的', emoji: '👋', sentence: 'The face is familiar.', sentenceZh: '这张脸很熟悉。' },
        { en: 'strange', phonetic: '/streɪndʒ/', zh: '奇怪的', emoji: '👽', sentence: 'It is strange.', sentenceZh: '很奇怪。' },
        { en: 'ordinary', phonetic: '/ˈɔːdnri/', zh: '普通的', emoji: '😐', sentence: 'It is an ordinary day.', sentenceZh: '这是普通的一天。' },
        { en: 'special', phonetic: '/ˈspeʃl/', zh: '特别的', emoji: '🌟', sentence: 'Today is special.', sentenceZh: '今天很特别。' },
        { en: 'terrible', phonetic: '/ˈterəbl/', zh: '糟糕的', emoji: '😨', sentence: 'The weather is terrible.', sentenceZh: '天气很糟。' },
        { en: 'wonderful', phonetic: '/ˈwʌndəfl/', zh: '极好的', emoji: '🤩', sentence: 'It is wonderful!', sentenceZh: '太棒了！' },
        { en: 'awful', phonetic: '/ˈɔːfl/', zh: '极坏的', emoji: '😧', sentence: 'The food is awful.', sentenceZh: '食物很难吃。' },
        { en: 'fantastic', phonetic: '/fænˈtæstɪk/', zh: '极好的', emoji: '🎆', sentence: 'The show is fantastic.', sentenceZh: '表演极好。' },
        { en: 'brilliant', phonetic: '/ˈbrɪliənt/', zh: '杰出的', emoji: '💎', sentence: 'She is brilliant.', sentenceZh: '她很杰出。' },
        { en: 'popular', phonetic: '/ˈpɒpjələr/', zh: '受欢迎的', emoji: '⭐', sentence: 'The song is popular.', sentenceZh: '这首歌很流行。' },
        { en: 'rare', phonetic: '/reər/', zh: '稀有的', emoji: '🦄', sentence: 'It is a rare bird.', sentenceZh: '这是稀有鸟类。' },
        { en: 'common', phonetic: '/ˈkɒmən/', zh: '常见的', emoji: '🌱', sentence: 'It is common.', sentenceZh: '很常见。' },
        { en: 'safe', phonetic: '/seɪf/', zh: '安全的', emoji: '🛡️', sentence: 'The place is safe.', sentenceZh: '这地方很安全。' }
      ]
    },
    {
      id: 'ms-adverbs', name: '⏱️ 副词与频度', icon: '⏱️', level: 'middle',
      items: [
        { en: 'always', phonetic: '/ˈɔːlweɪz/', zh: '总是', emoji: '♾️', sentence: 'I always wake up early.', sentenceZh: '我总是早起。' },
        { en: 'usually', phonetic: '/ˈjuːʒuəli/', zh: '通常', emoji: '🔁', sentence: 'She usually walks.', sentenceZh: '她通常走路。' },
        { en: 'often', phonetic: '/ˈɒfn/', zh: '经常', emoji: '📈', sentence: 'We often play.', sentenceZh: '我们经常玩。' },
        { en: 'sometimes', phonetic: '/ˈsʌmtaɪmz/', zh: '有时', emoji: '🌗', sentence: 'I sometimes read.', sentenceZh: '我有时读书。' },
        { en: 'seldom', phonetic: '/ˈseldəm/', zh: '很少', emoji: '📉', sentence: 'He seldom lies.', sentenceZh: '他很少说谎。' },
        { en: 'never', phonetic: '/ˈnevər/', zh: '从不', emoji: '🚫', sentence: 'I never give up.', sentenceZh: '我从不放弃。' },
        { en: 'quickly', phonetic: '/ˈkwɪkli/', zh: '快速地', emoji: '⚡', sentence: 'Run quickly!', sentenceZh: '快跑！' },
        { en: 'slowly', phonetic: '/ˈsləʊli/', zh: '缓慢地', emoji: '🐢', sentence: 'Walk slowly.', sentenceZh: '慢慢走。' },
        { en: 'carefully', phonetic: '/ˈkeəfəli/', zh: '小心地', emoji: '🧐', sentence: 'Drive carefully.', sentenceZh: '小心驾驶。' },
        { en: 'carelessly', phonetic: '/ˈkeələsli/', zh: '粗心地', emoji: '🙀', sentence: 'He did it carelessly.', sentenceZh: '他做得很粗心。' },
        { en: 'easily', phonetic: '/ˈiːzəli/', zh: '容易地', emoji: '🙂', sentence: 'I can do it easily.', sentenceZh: '我能轻易做到。' },
        { en: 'hardly', phonetic: '/ˈhɑːdli/', zh: '几乎不', emoji: '🙅', sentence: 'I hardly know him.', sentenceZh: '我几乎不认识他。' },
        { en: 'almost', phonetic: '/ˈɔːlməʊst/', zh: '几乎', emoji: '🔢', sentence: 'It is almost done.', sentenceZh: '几乎完成了。' },
        { en: 'already', phonetic: '/ɔːlˈredi/', zh: '已经', emoji: '✅', sentence: 'I already ate.', sentenceZh: '我已经吃了。' },
        { en: 'yet', phonetic: '/jet/', zh: '还（没）', emoji: '⏳', sentence: 'Not yet.', sentenceZh: '还没有。' },
        { en: 'still', phonetic: '/stɪl/', zh: '仍然', emoji: '🔄', sentence: 'He is still here.', sentenceZh: '他还在。' },
        { en: 'soon', phonetic: '/suːn/', zh: '很快', emoji: '⏭️', sentence: 'See you soon.', sentenceZh: '很快见。' },
        { en: 'suddenly', phonetic: '/ˈsʌdənli/', zh: '突然', emoji: '❗', sentence: 'It rained suddenly.', sentenceZh: '突然下雨了。' },
        { en: 'finally', phonetic: '/ˈfaɪnəli/', zh: '最后', emoji: '🏁', sentence: 'Finally we won.', sentenceZh: '最后我们赢了。' },
        { en: 'eventually', phonetic: '/ɪˈventʃuəli/', zh: '最终', emoji: '🎯', sentence: 'He came eventually.', sentenceZh: '他最终来了。' },
        { en: 'recently', phonetic: '/ˈriːsntli/', zh: '最近', emoji: '📅', sentence: 'I saw him recently.', sentenceZh: '我最近见过他。' },
        { en: 'currently', phonetic: '/ˈkʌrəntli/', zh: '目前', emoji: '📍', sentence: 'She is currently busy.', sentenceZh: '她目前很忙。' },
        { en: 'immediately', phonetic: '/ɪˈmiːdiətli/', zh: '立即', emoji: '⚡', sentence: 'Come immediately!', sentenceZh: '立刻来！' },
        { en: 'temporarily', phonetic: '/ˈtemprərəli/', zh: '暂时', emoji: '⏸️', sentence: 'It is closed temporarily.', sentenceZh: '暂时关闭。' },
        { en: 'permanently', phonetic: '/ˈpɜːmənəntli/', zh: '永久地', emoji: '♾️', sentence: 'He left permanently.', sentenceZh: '他永久离开了。' },
        { en: 'everywhere', phonetic: '/ˈevriweər/', zh: '到处', emoji: '🌐', sentence: 'Flowers are everywhere.', sentenceZh: '到处是花。' },
        { en: 'nowhere', phonetic: '/ˈnəʊweər/', zh: '无处', emoji: '🏜️', sentence: 'He is nowhere.', sentenceZh: '他无处可寻。' },
        { en: 'instead', phonetic: '/ɪnˈsted/', zh: '代替', emoji: '↔️', sentence: 'Have tea instead.', sentenceZh: '改喝茶吧。' }
      ]
    },
    {
      id: 'ms-nature-env', name: '🌍 自然环境', icon: '🌍', level: 'middle',
      items: [
        { en: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', zh: '环境', emoji: '🌳', sentence: 'Protect the environment.', sentenceZh: '保护环境。' },
        { en: 'pollution', phonetic: '/pəˈluːʃn/', zh: '污染', emoji: '🌫️', sentence: 'Air pollution is bad.', sentenceZh: '空气污染很严重。' },
        { en: 'climate', phonetic: '/ˈklaɪmət/', zh: '气候', emoji: '🌤️', sentence: 'The climate is changing.', sentenceZh: '气候在变化。' },
        { en: 'temperature', phonetic: '/ˈtemprətʃər/', zh: '温度', emoji: '🌡️', sentence: 'Check the temperature.', sentenceZh: '查温度。' },
        { en: 'hurricane', phonetic: '/ˈhʌrɪkən/', zh: '飓风', emoji: '🌀', sentence: 'A hurricane is coming.', sentenceZh: '飓风要来了。' },
        { en: 'earthquake', phonetic: '/ˈɜːθkweɪk/', zh: '地震', emoji: '🏚️', sentence: 'An earthquake struck.', sentenceZh: '发生了地震。' },
        { en: 'flood', phonetic: '/flʌd/', zh: '洪水', emoji: '🌊', sentence: 'The flood was big.', sentenceZh: '洪水很大。' },
        { en: 'drought', phonetic: '/draʊt/', zh: '干旱', emoji: '🏜️', sentence: 'A drought hurt the crops.', sentenceZh: '干旱伤了庄稼。' },
        { en: 'volcano', phonetic: '/vɒlˈkeɪnəʊ/', zh: '火山', emoji: '🌋', sentence: 'The volcano erupted.', sentenceZh: '火山喷发了。' },
        { en: 'glacier', phonetic: '/ˈɡlæsiər/', zh: '冰川', emoji: '🧊', sentence: 'The glacier is melting.', sentenceZh: '冰川在融化。' },
        { en: 'ocean', phonetic: '/ˈəʊʃn/', zh: '海洋', emoji: '🌊', sentence: 'The ocean is deep.', sentenceZh: '海洋很深。' },
        { en: 'desert', phonetic: '/ˈdezət/', zh: '沙漠', emoji: '🏜️', sentence: 'The desert is hot.', sentenceZh: '沙漠很热。' },
        { en: 'valley', phonetic: '/ˈvæli/', zh: '山谷', emoji: '⛰️', sentence: 'The valley is green.', sentenceZh: '山谷很绿。' },
        { en: 'waterfall', phonetic: '/ˈwɔːtəfɔːl/', zh: '瀑布', emoji: '💦', sentence: 'The waterfall is tall.', sentenceZh: '瀑布很高。' },
        { en: 'continent', phonetic: '/ˈkɒntɪnənt/', zh: '大洲', emoji: '🗺️', sentence: 'Asia is a continent.', sentenceZh: '亚洲是大洲。' },
        { en: 'island', phonetic: '/ˈaɪlənd/', zh: '岛屿', emoji: '🏝️', sentence: 'We visited an island.', sentenceZh: '我们参观了一个岛。' },
        { en: 'resource', phonetic: '/rɪˈsɔːs/', zh: '资源', emoji: '📦', sentence: 'Water is a resource.', sentenceZh: '水是资源。' },
        { en: 'recycle', phonetic: '/ˌriːˈsaɪkl/', zh: '回收', emoji: '♻️', sentence: 'Recycle the paper.', sentenceZh: '回收纸张。' },
        { en: 'protect', phonetic: '/prəˈtekt/', zh: '保护', emoji: '🛡️', sentence: 'Protect animals.', sentenceZh: '保护动物。' },
        { en: 'destroy', phonetic: '/dɪˈstrɔɪ/', zh: '破坏', emoji: '💥', sentence: 'Don\'t destroy nature.', sentenceZh: '别破坏自然。' },
        { en: 'preserve', phonetic: '/prɪˈzɜːv/', zh: '保存', emoji: '🫙', sentence: 'Preserve the forest.', sentenceZh: '保护森林。' },
        { en: 'endangered', phonetic: '/ɪnˈdeɪndʒərd/', zh: '濒危的', emoji: '🐼', sentence: 'Pandas are endangered.', sentenceZh: '熊猫濒危。' },
        { en: 'species', phonetic: '/ˈspiːʃiːz/', zh: '物种', emoji: '🦒', sentence: 'Many species exist.', sentenceZh: '有许多物种。' },
        { en: 'habitat', phonetic: '/ˈhæbɪtæt/', zh: '栖息地', emoji: '🌳', sentence: 'The forest is their habitat.', sentenceZh: '森林是它们的栖息地。' },
        { en: 'atmosphere', phonetic: '/ˈætməsfɪər/', zh: '大气', emoji: '🌫️', sentence: 'The atmosphere protects us.', sentenceZh: '大气保护我们。' },
        { en: 'ecosystem', phonetic: '/ˈiːkəʊsɪstəm/', zh: '生态系统', emoji: '🌱', sentence: 'The ecosystem is balanced.', sentenceZh: '生态系统平衡。' },
        { en: 'global', phonetic: '/ˈɡləʊbl/', zh: '全球的', emoji: '🌐', sentence: 'It is a global issue.', sentenceZh: '这是全球问题。' },
        { en: 'warming', phonetic: '/ˈwɔːmɪŋ/', zh: '变暖', emoji: '🔥', sentence: 'Global warming is real.', sentenceZh: '全球变暖是真的。' },
        { en: 'green', phonetic: '/ɡriːn/', zh: '环保的', emoji: '💚', sentence: 'Go green!', sentenceZh: '走向环保！' },
        { en: 'earth', phonetic: '/ɜːθ/', zh: '地球', emoji: '🌍', sentence: 'Love our earth.', sentenceZh: '爱我们的地球。' },
        { en: 'energy', phonetic: '/ˈenədʒi/', zh: '能源', emoji: '⚡', sentence: 'Save energy.', sentenceZh: '节约能源。' },
        { en: 'renewable', phonetic: '/rɪˈnjuːəbl/', zh: '可再生的', emoji: '♻️', sentence: 'Use renewable energy.', sentenceZh: '用可再生能源。' }
      ]
    },
    {
      id: 'ms-health', name: '🏥 健康医疗', icon: '🏥', level: 'middle',
      items: [
        { en: 'health', phonetic: '/helθ/', zh: '健康', emoji: '💪', sentence: 'Health is important.', sentenceZh: '健康很重要。' },
        { en: 'disease', phonetic: '/dɪˈziːz/', zh: '疾病', emoji: '🦠', sentence: 'The disease spread.', sentenceZh: '疾病传播了。' },
        { en: 'illness', phonetic: '/ˈɪlnəs/', zh: '病', emoji: '🤒', sentence: 'He has an illness.', sentenceZh: '他病了。' },
        { en: 'fever', phonetic: '/ˈfiːvər/', zh: '发烧', emoji: '🤒', sentence: 'She has a fever.', sentenceZh: '她发烧了。' },
        { en: 'cough', phonetic: '/kɒf/', zh: '咳嗽', emoji: '😷', sentence: 'I have a cough.', sentenceZh: '我咳嗽。' },
        { en: 'headache', phonetic: '/ˈhedeɪk/', zh: '头痛', emoji: '🤕', sentence: 'I have a headache.', sentenceZh: '我头痛。' },
        { en: 'stomachache', phonetic: '/ˈstʌməkeɪk/', zh: '肚子痛', emoji: '🤢', sentence: 'She has a stomachache.', sentenceZh: '她肚子痛。' },
        { en: 'medicine', phonetic: '/ˈmedsn/', zh: '药', emoji: '💊', sentence: 'Take the medicine.', sentenceZh: '吃药。' },
        { en: 'hospital', phonetic: '/ˈhɒspɪtl/', zh: '医院', emoji: '🏥', sentence: 'Go to the hospital.', sentenceZh: '去医院。' },
        { en: 'doctor', phonetic: '/ˈdɒktər/', zh: '医生', emoji: '👨‍⚕️', sentence: 'See a doctor.', sentenceZh: '看医生。' },
        { en: 'nurse', phonetic: '/nɜːs/', zh: '护士', emoji: '👩‍⚕️', sentence: 'The nurse is kind.', sentenceZh: '护士很和善。' },
        { en: 'patient', phonetic: '/ˈpeɪʃnt/', zh: '病人', emoji: '🛏️', sentence: 'The patient is resting.', sentenceZh: '病人在休息。' },
        { en: 'treatment', phonetic: '/ˈtriːtmənt/', zh: '治疗', emoji: '💉', sentence: 'The treatment worked.', sentenceZh: '治疗起效了。' },
        { en: 'surgery', phonetic: '/ˈsɜːdʒəri/', zh: '手术', emoji: '🔪', sentence: 'He needs surgery.', sentenceZh: '他需要手术。' },
        { en: 'injury', phonetic: '/ˈɪndʒəri/', zh: '伤', emoji: '🩹', sentence: 'He has an injury.', sentenceZh: '他受伤了。' },
        { en: 'wound', phonetic: '/wuːnd/', zh: '伤口', emoji: '🩹', sentence: 'Clean the wound.', sentenceZh: '清理伤口。' },
        { en: 'recover', phonetic: '/rɪˈkʌvər/', zh: '康复', emoji: '🙏', sentence: 'She will recover.', sentenceZh: '她会康复的。' },
        { en: 'virus', phonetic: '/ˈvaɪrəs/', zh: '病毒', emoji: '🦠', sentence: 'A virus spread.', sentenceZh: '病毒传播了。' },
        { en: 'infection', phonetic: '/ɪnˈfekʃn/', zh: '感染', emoji: '🤒', sentence: 'He has an infection.', sentenceZh: '他感染了。' },
        { en: 'allergy', phonetic: '/ˈælədʒi/', zh: '过敏', emoji: '🤧', sentence: 'I have an allergy.', sentenceZh: '我过敏。' },
        { en: 'nutrition', phonetic: '/njuːˈtrɪʃn/', zh: '营养', emoji: '🥗', sentence: 'Good nutrition matters.', sentenceZh: '营养很重要。' },
        { en: 'vitamin', phonetic: '/ˈvɪtəmɪn/', zh: '维生素', emoji: '🍊', sentence: 'Eat vitamins.', sentenceZh: '补充维生素。' },
        { en: 'exercise', phonetic: '/ˈeksəsaɪz/', zh: '锻炼', emoji: '🏃', sentence: 'Exercise every day.', sentenceZh: '每天锻炼。' },
        { en: 'diet', phonetic: '/ˈdaɪət/', zh: '饮食', emoji: '🥗', sentence: 'A healthy diet helps.', sentenceZh: '健康饮食有益。' },
        { en: 'mental', phonetic: '/ˈmentl/', zh: '心理的', emoji: '🧠', sentence: 'Mental health matters.', sentenceZh: '心理健康重要。' },
        { en: 'physical', phonetic: '/ˈfɪzɪkl/', zh: '身体的', emoji: '💪', sentence: 'Do physical exercise.', sentenceZh: '做体育锻炼。' },
        { en: 'disabled', phonetic: '/dɪsˈeɪbld/', zh: '残疾的', emoji: '♿', sentence: 'Help the disabled.', sentenceZh: '帮助残疾人。' },
        { en: 'emergency', phonetic: '/iˈmɜːdʒənsi/', zh: '紧急情况', emoji: '🚨', sentence: 'Call in an emergency.', sentenceZh: '紧急时打电话。' },
        { en: 'ambulance', phonetic: '/ˈæmbjələns/', zh: '救护车', emoji: '🚑', sentence: 'Call an ambulance.', sentenceZh: '叫救护车。' },
        { en: 'pharmacy', phonetic: '/ˈfɑːməsi/', zh: '药店', emoji: '💊', sentence: 'Buy it at the pharmacy.', sentenceZh: '在药店买。' },
        { en: 'cure', phonetic: '/kjʊər/', zh: '治愈', emoji: '✨', sentence: 'There is no cure yet.', sentenceZh: '尚无治愈方法。' },
        { en: 'symptom', phonetic: '/ˈsɪmptəm/', zh: '症状', emoji: '🤧', sentence: 'A fever is a symptom.', sentenceZh: '发烧是症状。' }
      ]
    },
    {
      id: 'ms-travel', name: '✈️ 交通旅行', icon: '✈️', level: 'middle',
      items: [
        { en: 'journey', phonetic: '/ˈdʒɜːni/', zh: '旅程', emoji: '🛤️', sentence: 'The journey was long.', sentenceZh: '旅程很长。' },
        { en: 'trip', phonetic: '/trɪp/', zh: '出行', emoji: '🧳', sentence: 'Have a good trip!', sentenceZh: '旅途愉快！' },
        { en: 'travel', phonetic: '/ˈtrævl/', zh: '旅行', emoji: '🌍', sentence: 'I love to travel.', sentenceZh: '我爱旅行。' },
        { en: 'tour', phonetic: '/tʊər/', zh: '旅游', emoji: '🗺️', sentence: 'Join the tour.', sentenceZh: '加入旅行团。' },
        { en: 'tourism', phonetic: '/ˈtʊərɪzəm/', zh: '旅游业', emoji: '🏖️', sentence: 'Tourism is big here.', sentenceZh: '这里旅游业很发达。' },
        { en: 'passenger', phonetic: '/ˈpæsɪndʒər/', zh: '乘客', emoji: '🧑‍✈️', sentence: 'Passengers, take your seats.', sentenceZh: '乘客请就座。' },
        { en: 'luggage', phonetic: '/ˈlʌɡɪdʒ/', zh: '行李', emoji: '🧳', sentence: 'Pack your luggage.', sentenceZh: '收拾行李。' },
        { en: 'suitcase', phonetic: '/ˈsuːtkeɪs/', zh: '手提箱', emoji: '🧳', sentence: 'Open the suitcase.', sentenceZh: '打开手提箱。' },
        { en: 'passport', phonetic: '/ˈpɑːspɔːt/', zh: '护照', emoji: '📔', sentence: 'Show your passport.', sentenceZh: '出示护照。' },
        { en: 'visa', phonetic: '/ˈviːzə/', zh: '签证', emoji: '📄', sentence: 'I need a visa.', sentenceZh: '我需要签证。' },
        { en: 'ticket', phonetic: '/ˈtɪkɪt/', zh: '票', emoji: '🎫', sentence: 'Buy a ticket.', sentenceZh: '买票。' },
        { en: 'board', phonetic: '/bɔːd/', zh: '登机', emoji: '✈️', sentence: 'Time to board.', sentenceZh: '登机时间到了。' },
        { en: 'depart', phonetic: '/dɪˈpɑːt/', zh: '出发', emoji: '🛫', sentence: 'We depart at six.', sentenceZh: '我们六点出发。' },
        { en: 'arrive', phonetic: '/əˈraɪv/', zh: '到达', emoji: '🛬', sentence: 'We arrive at noon.', sentenceZh: '我们中午到。' },
        { en: 'destination', phonetic: '/ˌdestɪˈneɪʃn/', zh: '目的地', emoji: '📍', sentence: 'We reached our destination.', sentenceZh: '我们到了目的地。' },
        { en: 'hotel', phonetic: '/həʊˈtel/', zh: '酒店', emoji: '🏨', sentence: 'Book a hotel.', sentenceZh: '订酒店。' },
        { en: 'motel', phonetic: '/məʊˈtel/', zh: '汽车旅馆', emoji: '🏚️', sentence: 'We stayed at a motel.', sentenceZh: '我们住汽车旅馆。' },
        { en: 'reserve', phonetic: '/rɪˈzɜːv/', zh: '预订', emoji: '📝', sentence: 'Reserve a room.', sentenceZh: '预订房间。' },
        { en: 'delay', phonetic: '/dɪˈleɪ/', zh: '延误', emoji: '⏰', sentence: 'The flight is delayed.', sentenceZh: '航班延误了。' },
        { en: 'souvenir', phonetic: '/ˌsuːvəˈnɪər/', zh: '纪念品', emoji: '🎁', sentence: 'Buy a souvenir.', sentenceZh: '买纪念品。' },
        { en: 'adventure', phonetic: '/ədˈventʃər/', zh: '冒险', emoji: '🗺️', sentence: 'An adventure awaits.', sentenceZh: '冒险在等着。' },
        { en: 'guide', phonetic: '/ɡaɪd/', zh: '导游', emoji: '🧭', sentence: 'The guide is helpful.', sentenceZh: '导游很有帮助。' },
        { en: 'route', phonetic: '/ruːt/', zh: '路线', emoji: '🛣️', sentence: 'Take this route.', sentenceZh: '走这条路线。' },
        { en: 'map', phonetic: '/mæp/', zh: '地图', emoji: '🗺️', sentence: 'Read the map.', sentenceZh: '看地图。' },
        { en: 'foreign', phonetic: '/ˈfɒrən/', zh: '外国的', emoji: '🌐', sentence: 'I love foreign food.', sentenceZh: '我喜欢外国食物。' },
        { en: 'abroad', phonetic: '/əˈbrɔːd/', zh: '在国外', emoji: '✈️', sentence: 'She studies abroad.', sentenceZh: '她在国外学习。' },
        { en: 'domestic', phonetic: '/dəˈmestɪk/', zh: '国内的', emoji: '🏠', sentence: 'Take a domestic flight.', sentenceZh: '搭国内航班。' },
        { en: 'itinerary', phonetic: '/aɪˈtɪnərəri/', zh: '行程', emoji: '📋', sentence: 'Check the itinerary.', sentenceZh: '查看行程。' },
        { en: 'agency', phonetic: '/ˈeɪdʒənsi/', zh: '旅行社', emoji: '🏢', sentence: 'Visit the agency.', sentenceZh: '去旅行社。' },
        { en: 'station', phonetic: '/ˈsteɪʃn/', zh: '车站', emoji: '🚉', sentence: 'Meet at the station.', sentenceZh: '在车站见。' },
        { en: 'flight', phonetic: '/flaɪt/', zh: '航班', emoji: '✈️', sentence: 'The flight is long.', sentenceZh: '航班很长。' },
        { en: 'vehicle', phonetic: '/ˈviːəkl/', zh: '车辆', emoji: '🚗', sentence: 'Park the vehicle.', sentenceZh: '停车。' }
      ]
    },
    {
      id: 'ms-economy', name: '💰 经济购物', icon: '💰', level: 'middle',
      items: [
        { en: 'money', phonetic: '/ˈmʌni/', zh: '钱', emoji: '💵', sentence: 'Save your money.', sentenceZh: '存钱。' },
        { en: 'cash', phonetic: '/kæʃ/', zh: '现金', emoji: '💴', sentence: 'Pay with cash.', sentenceZh: '付现金。' },
        { en: 'coin', phonetic: '/kɔɪn/', zh: '硬币', emoji: '🪙', sentence: 'I found a coin.', sentenceZh: '我找到一枚硬币。' },
        { en: 'bill', phonetic: '/bɪl/', zh: '账单', emoji: '🧾', sentence: 'Pay the bill.', sentenceZh: '付账单。' },
        { en: 'price', phonetic: '/praɪs/', zh: '价格', emoji: '🏷️', sentence: 'The price is high.', sentenceZh: '价格很高。' },
        { en: 'cost', phonetic: '/kɒst/', zh: '花费', emoji: '💸', sentence: 'What is the cost?', sentenceZh: '花费多少？' },
        { en: 'pay', phonetic: '/peɪ/', zh: '支付', emoji: '💳', sentence: 'Pay here.', sentenceZh: '在这付款。' },
        { en: 'buy', phonetic: '/baɪ/', zh: '买', emoji: '🛒', sentence: 'I want to buy it.', sentenceZh: '我想买。' },
        { en: 'sell', phonetic: '/sel/', zh: '卖', emoji: '🏷️', sentence: 'They sell fruit.', sentenceZh: '他们卖水果。' },
        { en: 'shop', phonetic: '/ʃɒp/', zh: '商店', emoji: '🏪', sentence: 'Go to the shop.', sentenceZh: '去商店。' },
        { en: 'store', phonetic: '/stɔːr/', zh: '店铺', emoji: '🏬', sentence: 'The store is open.', sentenceZh: '店铺开门了。' },
        { en: 'market', phonetic: '/ˈmɑːkɪt/', zh: '市场', emoji: '🪇', sentence: 'Visit the market.', sentenceZh: '逛市场。' },
        { en: 'mall', phonetic: '/mɔːl/', zh: '商场', emoji: '🏙️', sentence: 'We went to the mall.', sentenceZh: '我们去了商场。' },
        { en: 'customer', phonetic: '/ˈkʌstəmər/', zh: '顾客', emoji: '🧑', sentence: 'The customer is happy.', sentenceZh: '顾客很满意。' },
        { en: 'cashier', phonetic: '/kæˈʃɪər/', zh: '收银员', emoji: '🧑‍💼', sentence: 'Ask the cashier.', sentenceZh: '问收银员。' },
        { en: 'discount', phonetic: '/ˈdɪskaʊnt/', zh: '折扣', emoji: '🏷️', sentence: 'I got a discount.', sentenceZh: '我拿到了折扣。' },
        { en: 'sale', phonetic: '/seɪl/', zh: '促销', emoji: '🛍️', sentence: 'The sale starts today.', sentenceZh: '促销今天开始。' },
        { en: 'bargain', phonetic: '/ˈbɑːɡən/', zh: '便宜货', emoji: '🤝', sentence: 'It is a bargain.', sentenceZh: '很划算。' },
        { en: 'brand', phonetic: '/brænd/', zh: '品牌', emoji: '🏷️', sentence: 'I like this brand.', sentenceZh: '我喜欢这个品牌。' },
        { en: 'product', phonetic: '/ˈprɒdʌkt/', zh: '产品', emoji: '📦', sentence: 'The product is good.', sentenceZh: '产品很好。' },
        { en: 'quality', phonetic: '/ˈkwɒləti/', zh: '质量', emoji: '✨', sentence: 'Check the quality.', sentenceZh: '检查质量。' },
        { en: 'quantity', phonetic: '/ˈkwɒntəti/', zh: '数量', emoji: '🔢', sentence: 'A large quantity.', sentenceZh: '数量很多。' },
        { en: 'receipt', phonetic: '/rɪˈsiːt/', zh: '收据', emoji: '🧾', sentence: 'Keep the receipt.', sentenceZh: '保留收据。' },
        { en: 'refund', phonetic: '/ˈriːfʌnd/', zh: '退款', emoji: '↩️', sentence: 'I want a refund.', sentenceZh: '我要退款。' },
        { en: 'exchange', phonetic: '/ɪksˈtʃeɪndʒ/', zh: '交换', emoji: '🔄', sentence: 'Exchange the item.', sentenceZh: '换货。' },
        { en: 'afford', phonetic: '/əˈfɔːd/', zh: '买得起', emoji: '💰', sentence: 'I can afford it.', sentenceZh: '我买得起。' },
        { en: 'expensive', phonetic: '/ɪkˈspensɪv/', zh: '昂贵的', emoji: '💎', sentence: 'It is expensive.', sentenceZh: '很贵。' },
        { en: 'cheap', phonetic: '/tʃiːp/', zh: '便宜的', emoji: '🏷️', sentence: 'It is cheap.', sentenceZh: '很便宜。' }
      ]
    },
    {
      id: 'ms-media', name: '📺 媒体娱乐', icon: '📺', level: 'middle',
      items: [
        { en: 'news', phonetic: '/njuːz/', zh: '新闻', emoji: '📰', sentence: 'Watch the news.', sentenceZh: '看新闻。' },
        { en: 'newspaper', phonetic: '/ˈnjuːzpeɪpər/', zh: '报纸', emoji: '🗞️', sentence: 'Read the newspaper.', sentenceZh: '读报纸。' },
        { en: 'magazine', phonetic: '/ˌmæɡəˈziːn/', zh: '杂志', emoji: '📖', sentence: 'She reads magazines.', sentenceZh: '她读杂志。' },
        { en: 'television', phonetic: '/ˈtelɪvɪʃn/', zh: '电视', emoji: '📺', sentence: 'Turn on the television.', sentenceZh: '开电视。' },
        { en: 'radio', phonetic: '/ˈreɪdiəʊ/', zh: '收音机', emoji: '📻', sentence: 'Listen to the radio.', sentenceZh: '听收音机。' },
        { en: 'channel', phonetic: '/ˈtʃænl/', zh: '频道', emoji: '📡', sentence: 'Change the channel.', sentenceZh: '换频道。' },
        { en: 'program', phonetic: '/ˈprəʊɡræm/', zh: '节目', emoji: '📽️', sentence: 'A good program.', sentenceZh: '好节目。' },
        { en: 'movie', phonetic: '/ˈmuːvi/', zh: '电影', emoji: '🎬', sentence: 'Let\'s watch a movie.', sentenceZh: '我们看电影吧。' },
        { en: 'film', phonetic: '/fɪlm/', zh: '影片', emoji: '🎞️', sentence: 'The film is long.', sentenceZh: '影片很长。' },
        { en: 'actor', phonetic: '/ˈæktər/', zh: '男演员', emoji: '🤵', sentence: 'He is a famous actor.', sentenceZh: '他是名演员。' },
        { en: 'actress', phonetic: '/ˈæktrəs/', zh: '女演员', emoji: '👸', sentence: 'She is an actress.', sentenceZh: '她是女演员。' },
        { en: 'director', phonetic: '/dəˈrektər/', zh: '导演', emoji: '🎬', sentence: 'The director is great.', sentenceZh: '导演很棒。' },
        { en: 'character', phonetic: '/ˈkærəktər/', zh: '角色', emoji: '🎭', sentence: 'My favorite character.', sentenceZh: '我最喜欢的角色。' },
        { en: 'scene', phonetic: '/siːn/', zh: '场景', emoji: '🏞️', sentence: 'A beautiful scene.', sentenceZh: '美丽的场景。' },
        { en: 'song', phonetic: '/sɒŋ/', zh: '歌曲', emoji: '🎵', sentence: 'Sing a song.', sentenceZh: '唱首歌。' },
        { en: 'concert', phonetic: '/ˈkɒnsət/', zh: '音乐会', emoji: '🎤', sentence: 'Go to a concert.', sentenceZh: '去音乐会。' },
        { en: 'instrument', phonetic: '/ˈɪnstrəmənt/', zh: '乐器', emoji: '🎸', sentence: 'Play an instrument.', sentenceZh: '弹乐器。' },
        { en: 'article', phonetic: '/ˈɑːtɪkl/', zh: '文章', emoji: '📄', sentence: 'Read the article.', sentenceZh: '读文章。' },
        { en: 'report', phonetic: '/rɪˈpɔːt/', zh: '报道', emoji: '📊', sentence: 'Write a report.', sentenceZh: '写报道。' },
        { en: 'interview', phonetic: '/ˈɪntəvjuː/', zh: '采访', emoji: '🎙️', sentence: 'An interview with the star.', sentenceZh: '采访明星。' },
        { en: 'journal', phonetic: '/ˈdʒɜːnl/', zh: '期刊', emoji: '📔', sentence: 'A science journal.', sentenceZh: '科学期刊。' },
        { en: 'blog', phonetic: '/blɒɡ/', zh: '博客', emoji: '💻', sentence: 'She writes a blog.', sentenceZh: '她写博客。' },
        { en: 'social', phonetic: '/ˈsəʊʃl/', zh: '社交的', emoji: '💬', sentence: 'Social media is popular.', sentenceZh: '社交媒体很流行。' },
        { en: 'media', phonetic: '/ˈmiːdiə/', zh: '媒体', emoji: '📡', sentence: 'The media reported it.', sentenceZh: '媒体报导了。' },
        { en: 'video', phonetic: '/ˈvɪdiəʊ/', zh: '视频', emoji: '📹', sentence: 'Watch the video.', sentenceZh: '看视频。' },
        { en: 'cartoon', phonetic: '/kɑːˈtuːn/', zh: '动画片', emoji: '🎞️', sentence: 'Kids love cartoons.', sentenceZh: '孩子爱看动画。' },
        { en: 'game', phonetic: '/ɡeɪm/', zh: '游戏', emoji: '🎮', sentence: 'Play a game.', sentenceZh: '玩游戏。' },
        { en: 'stage', phonetic: '/steɪdʒ/', zh: '舞台', emoji: '🎭', sentence: 'She is on stage.', sentenceZh: '她在台上。' }
      ]
    },
    {
      id: 'ms-jobs-adv', name: '💼 职业进阶', icon: '💼', level: 'middle',
      items: [
        { en: 'career', phonetic: '/kəˈrɪər/', zh: '职业', emoji: '📈', sentence: 'She has a great career.', sentenceZh: '她事业很好。' },
        { en: 'profession', phonetic: '/prəˈfeʃn/', zh: '专业', emoji: '🎓', sentence: 'Teaching is a profession.', sentenceZh: '教学是门专业。' },
        { en: 'occupation', phonetic: '/ˌɒkjuˈpeɪʃn/', zh: '职业', emoji: '👔', sentence: 'What is your occupation?', sentenceZh: '你的职业是什么？' },
        { en: 'employee', phonetic: '/ɪmˈplɔɪiː/', zh: '雇员', emoji: '🧑‍💼', sentence: 'He is an employee.', sentenceZh: '他是雇员。' },
        { en: 'employer', phonetic: '/ɪmˈplɔɪər/', zh: '雇主', emoji: '🏢', sentence: 'The employer is fair.', sentenceZh: '雇主很公正。' },
        { en: 'manager', phonetic: '/ˈmænɪdʒər/', zh: '经理', emoji: '🕴️', sentence: 'The manager is busy.', sentenceZh: '经理很忙。' },
        { en: 'boss', phonetic: '/bɒs/', zh: '老板', emoji: '🧑‍💼', sentence: 'My boss is kind.', sentenceZh: '我老板很和善。' },
        { en: 'colleague', phonetic: '/ˈkɒliːɡ/', zh: '同事', emoji: '👥', sentence: 'She is my colleague.', sentenceZh: '她是我同事。' },
        { en: 'staff', phonetic: '/stɑːf/', zh: '员工', emoji: '👨‍👩‍👧‍👦', sentence: 'The staff is helpful.', sentenceZh: '员工很有帮助。' },
        { en: 'interview', phonetic: '/ˈɪntəvjuː/', zh: '面试', emoji: '🗣️', sentence: 'I have an interview.', sentenceZh: '我有面试。' },
        { en: 'salary', phonetic: '/ˈsæləri/', zh: '薪水', emoji: '💰', sentence: 'He got a high salary.', sentenceZh: '他薪水高。' },
        { en: 'wage', phonetic: '/weɪdʒ/', zh: '工资', emoji: '💵', sentence: 'Daily wage is low.', sentenceZh: '日工资很低。' },
        { en: 'income', phonetic: '/ˈɪnkʌm/', zh: '收入', emoji: '💹', sentence: 'His income rose.', sentenceZh: '他的收入涨了。' },
        { en: 'business', phonetic: '/ˈbɪznəs/', zh: '生意', emoji: '💼', sentence: 'He runs a business.', sentenceZh: '他做生意。' },
        { en: 'company', phonetic: '/ˈkʌmpəni/', zh: '公司', emoji: '🏢', sentence: 'She works in a company.', sentenceZh: '她在公司上班。' },
        { en: 'factory', phonetic: '/ˈfæktri/', zh: '工厂', emoji: '🏭', sentence: 'The factory is big.', sentenceZh: '工厂很大。' },
        { en: 'office', phonetic: '/ˈɒfɪs/', zh: '办公室', emoji: '🏢', sentence: 'I go to the office.', sentenceZh: '我去办公室。' },
        { en: 'industry', phonetic: '/ˈɪndəstri/', zh: '工业', emoji: '🏗️', sentence: 'The industry is growing.', sentenceZh: '工业在增长。' },
        { en: 'retire', phonetic: '/rɪˈtaɪər/', zh: '退休', emoji: '🌅', sentence: 'He will retire soon.', sentenceZh: '他快退休了。' },
        { en: 'hire', phonetic: '/ˈhaɪər/', zh: '雇用', emoji: '🤝', sentence: 'They hire new staff.', sentenceZh: '他们招新人。' },
        { en: 'fire', phonetic: '/ˈfaɪər/', zh: '解雇', emoji: '❌', sentence: 'He was fired.', sentenceZh: '他被解雇了。' },
        { en: 'resign', phonetic: '/rɪˈzaɪn/', zh: '辞职', emoji: '🚪', sentence: 'She resigned.', sentenceZh: '她辞职了。' },
        { en: 'promote', phonetic: '/prəˈməʊt/', zh: '晋升', emoji: '⬆️', sentence: 'He was promoted.', sentenceZh: '他晋升了。' },
        { en: 'qualify', phonetic: '/ˈkwɒlɪfaɪ/', zh: '取得资格', emoji: '🎖️', sentence: 'She qualified as a doctor.', sentenceZh: '她取得了医生资格。' },
        { en: 'experienced', phonetic: '/ɪkˈspɪəriənst/', zh: '有经验的', emoji: '🧓', sentence: 'He is experienced.', sentenceZh: '他经验丰富。' },
        { en: 'skilled', phonetic: '/skɪld/', zh: '熟练的', emoji: '🛠️', sentence: 'She is skilled.', sentenceZh: '她很熟练。' },
        { en: 'professional', phonetic: '/prəˈfeʃənl/', zh: '专业的', emoji: '👔', sentence: 'A professional team.', sentenceZh: '专业团队。' },
        { en: 'successful', phonetic: '/səkˈsesfl/', zh: '成功的', emoji: '🏆', sentence: 'She is successful.', sentenceZh: '她很成功。' },
        { en: 'interviewer', phonetic: '/ˈɪntəvjuːər/', zh: '面试官', emoji: '🧑‍⚖️', sentence: 'The interviewer smiled.', sentenceZh: '面试官笑了。' },
        { en: 'applicant', phonetic: '/ˈæplɪkənt/', zh: '申请人', emoji: '🧑', sentence: 'An applicant came.', sentenceZh: '一位申请人来了。' },
        { en: 'contract', phonetic: '/ˈkɒntrækt/', zh: '合同', emoji: '📝', sentence: 'Sign the contract.', sentenceZh: '签合同。' },
        { en: 'duty', phonetic: '/ˈdjuːti/', zh: '职责', emoji: '📋', sentence: 'It is my duty.', sentenceZh: '这是我的职责。' }
      ]
    },
    {
      id: 'ms-time-events', name: '🎉 时间节庆', icon: '🎉', level: 'middle',
      items: [
        { en: 'century', phonetic: '/ˈsentʃəri/', zh: '世纪', emoji: '💯', sentence: 'A new century began.', sentenceZh: '新世纪开始了。' },
        { en: 'decade', phonetic: '/ˈdekeɪd/', zh: '十年', emoji: '🔟', sentence: 'A decade passed.', sentenceZh: '十年过去了。' },
        { en: 'season', phonetic: '/ˈsiːzn/', zh: '季节', emoji: '🍂', sentence: 'My favorite season is autumn.', sentenceZh: '我最喜欢秋天。' },
        { en: 'spring', phonetic: '/sprɪŋ/', zh: '春天', emoji: '🌸', sentence: 'Flowers bloom in spring.', sentenceZh: '春天开花。' },
        { en: 'summer', phonetic: '/ˈsʌmər/', zh: '夏天', emoji: '☀️', sentence: 'Summer is hot.', sentenceZh: '夏天很热。' },
        { en: 'autumn', phonetic: '/ˈɔːtəm/', zh: '秋天', emoji: '🍁', sentence: 'Leaves fall in autumn.', sentenceZh: '秋天落叶。' },
        { en: 'winter', phonetic: '/ˈwɪntər/', zh: '冬天', emoji: '❄️', sentence: 'Winter is cold.', sentenceZh: '冬天很冷。' },
        { en: 'vacation', phonetic: '/vəˈkeɪʃn/', zh: '假期', emoji: '🏖️', sentence: 'Summer vacation is fun.', sentenceZh: '暑假很好玩。' },
        { en: 'festival', phonetic: '/ˈfestɪvl/', zh: '节日', emoji: '🎊', sentence: 'A spring festival.', sentenceZh: '春节。' },
        { en: 'birthday', phonetic: '/ˈbɜːθdeɪ/', zh: '生日', emoji: '🎂', sentence: 'Happy birthday!', sentenceZh: '生日快乐！' },
        { en: 'anniversary', phonetic: '/ˌænɪˈvɜːsəri/', zh: '周年纪念', emoji: '💝', sentence: 'Our anniversary.', sentenceZh: '我们的纪念日。' },
        { en: 'wedding', phonetic: '/ˈwedɪŋ/', zh: '婚礼', emoji: '💒', sentence: 'A beautiful wedding.', sentenceZh: '美丽的婚礼。' },
        { en: 'graduation', phonetic: '/ˌɡrædʒuˈeɪʃn/', zh: '毕业', emoji: '🎓', sentence: 'Graduation day.', sentenceZh: '毕业日。' },
        { en: 'ceremony', phonetic: '/ˈserəməni/', zh: '典礼', emoji: '🎊', sentence: 'The ceremony was grand.', sentenceZh: '典礼很隆重。' },
        { en: 'celebrate', phonetic: '/ˈselɪbreɪt/', zh: '庆祝', emoji: '🎉', sentence: 'We celebrate together.', sentenceZh: '我们一起庆祝。' },
        { en: 'tradition', phonetic: '/trəˈdɪʃn/', zh: '传统', emoji: '🎎', sentence: 'A long tradition.', sentenceZh: '悠久的传统。' },
        { en: 'custom', phonetic: '/ˈkʌstəm/', zh: '习俗', emoji: '🏮', sentence: 'A local custom.', sentenceZh: '当地习俗。' },
        { en: 'schedule', phonetic: '/ˈʃedjuːl/', zh: '日程', emoji: '📅', sentence: 'Check the schedule.', sentenceZh: '查日程。' },
        { en: 'deadline', phonetic: '/ˈdedlaɪn/', zh: '截止日期', emoji: '⏰', sentence: 'Meet the deadline.', sentenceZh: '赶上截止日期。' },
        { en: 'period', phonetic: '/ˈpɪəriəd/', zh: '时期', emoji: '⏳', sentence: 'A long period.', sentenceZh: '很长一段时期。' },
        { en: 'phase', phonetic: '/feɪz/', zh: '阶段', emoji: '🔄', sentence: 'A new phase.', sentenceZh: '新阶段。' },
        { en: 'stage', phonetic: '/steɪdʒ/', zh: '阶段', emoji: '🪜', sentence: 'The next stage.', sentenceZh: '下一阶段。' },
        { en: 'generation', phonetic: '/ˌdʒenəˈreɪʃn/', zh: '一代', emoji: '👪', sentence: 'A new generation.', sentenceZh: '新一代。' },
        { en: 'ancient', phonetic: '/ˈeɪnʃənt/', zh: '古代的', emoji: '🏺', sentence: 'Ancient times.', sentenceZh: '古代。' },
        { en: 'modern', phonetic: '/ˈmɒdn/', zh: '现代的', emoji: '🏙️', sentence: 'Modern life.', sentenceZh: '现代生活。' },
        { en: 'moment', phonetic: '/ˈməʊmənt/', zh: '时刻', emoji: '⏱️', sentence: 'A happy moment.', sentenceZh: '快乐时刻。' },
        { en: 'midnight', phonetic: '/ˈmɪdnaɪt/', zh: '午夜', emoji: '🌃', sentence: 'At midnight.', sentenceZh: '在午夜。' },
        { en: 'dawn', phonetic: '/dɔːn/', zh: '黎明', emoji: '🌅', sentence: 'At dawn.', sentenceZh: '在黎明。' }
      ]
    },
    {
      id: 'phrases-middle', name: '💬 中学短句', icon: '💬', level: 'middle',
      items: [
        { en: 'Could you do me a favor?', zh: '能帮我个忙吗？', emoji: '🤝', sentence: '', sentenceZh: '' },
        { en: 'I am looking forward to it.', zh: '我很期待。', emoji: '⭐', sentence: '', sentenceZh: '' },
        { en: 'What do you mean by that?', zh: '你那样说是什么意思？', emoji: '❓', sentence: '', sentenceZh: '' },
        { en: 'It depends on the weather.', zh: '这取决于天气。', emoji: '🌤️', sentence: '', sentenceZh: '' },
        { en: 'I am proud of you.', zh: '我为你骄傲。', emoji: '😊', sentence: '', sentenceZh: '' },
        { en: 'Do you mind if I sit here?', zh: '你介意我坐这儿吗？', emoji: '🪑', sentence: '', sentenceZh: '' },
        { en: 'Let me think it over.', zh: '让我仔细想想。', emoji: '🤔', sentence: '', sentenceZh: '' },
        { en: 'It is none of your business.', zh: '这不关你的事。', emoji: '🚫', sentence: '', sentenceZh: '' },
        { en: 'I cannot agree with you more.', zh: '我完全同意。', emoji: '✅', sentence: '', sentenceZh: '' },
        { en: 'What is the matter with you?', zh: '你怎么了？', emoji: '😟', sentence: '', sentenceZh: '' },
        { en: 'Keep up the good work!', zh: '继续保持！', emoji: '💪', sentence: '', sentenceZh: '' },
        { en: 'It is a piece of cake.', zh: '小菜一碟。', emoji: '🍰', sentence: '', sentenceZh: '' },
        { en: 'Do not give up halfway.', zh: '不要半途而废。', emoji: '🏁', sentence: '', sentenceZh: '' },
        { en: 'Practice makes perfect.', zh: '熟能生巧。', emoji: '🎯', sentence: '', sentenceZh: '' },
        { en: 'Better late than never.', zh: '迟做总比不做好。', emoji: '⏰', sentence: '', sentenceZh: '' },
        { en: 'Actions speak louder than words.', zh: '行动胜于言辞。', emoji: '🗣️', sentence: '', sentenceZh: '' },
        { en: 'Where there is a will, there is a way.', zh: '有志者事竟成。', emoji: '🌟', sentence: '', sentenceZh: '' },
        { en: 'I will be right back.', zh: '我马上回来。', emoji: '🔙', sentence: '', sentenceZh: '' },
        { en: 'It is worth trying.', zh: '值得一试。', emoji: '💎', sentence: '', sentenceZh: '' },
        { en: 'Take it easy.', zh: '别紧张。', emoji: '😌', sentence: '', sentenceZh: '' }
      ]
    },
    {
      id: 'dialogue-middle', name: '🗣️ 中学情景对话', icon: '🗣️', level: 'middle',
      items: [
        { en: 'How was your weekend?', zh: '你周末过得怎么样？', emoji: '📅', sentence: 'It was great. I went hiking.', sentenceZh: '很棒，我去爬山了。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'What do you think of the movie?', zh: '你觉得这部电影怎么样？', emoji: '🎬', sentence: 'I think it is exciting.', sentenceZh: '我觉得很刺激。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'Could you tell me the way to the station?', zh: '能告诉我去车站的路吗？', emoji: '🚉', sentence: 'Go straight and turn left.', sentenceZh: '直走然后左转。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'What are you going to be in the future?', zh: '你将来想做什么？', emoji: '🔮', sentence: 'I want to be a scientist.', sentenceZh: '我想当科学家。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'Why are you learning English?', zh: '你为什么学英语？', emoji: '📚', sentence: 'Because it is useful.', sentenceZh: '因为它很有用。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'Have you ever been to Beijing?', zh: '你去过北京吗？', emoji: '🏙️', sentence: 'Yes, I went there last year.', sentenceZh: '是的，我去年去过。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'What is your favorite book?', zh: '你最喜欢的书是什么？', emoji: '📖', sentence: 'My favorite is Harry Potter.', sentenceZh: '我最喜欢哈利波特。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'Do you like sports?', zh: '你喜欢运动吗？', emoji: '⚽', sentence: 'Yes, I play basketball every day.', sentenceZh: '是的，我每天打篮球。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'What should I do now?', zh: '我现在该怎么办？', emoji: '🤔', sentence: 'You should ask your teacher.', sentenceZh: '你应该问老师。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'May I borrow your dictionary?', zh: '可以借你的字典吗？', emoji: '📕', sentence: 'Sure, here you are.', sentenceZh: '当然，给你。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'How do you study English?', zh: '你怎么学英语？', emoji: '✏️', sentence: 'I read English every morning.', sentenceZh: '我每天早上读英语。', roleA: 'Tom', roleB: 'Lucy' },
        { en: 'What is your dream?', zh: '你的梦想是什么？', emoji: '🌟', sentence: 'I want to travel the world.', sentenceZh: '我想环游世界。', roleA: 'Tom', roleB: 'Lucy' }
      ]
    },
    {
      id: 'stories-middle', name: '📖 中学英语美文', icon: '📖', level: 'middle',
      items: [
        { en: 'The Value of Time', zh: '时间的价值', emoji: '⏰', story: 'Time is one of the most valuable things in our lives. Once it is gone, it will never come back. Many people waste time on useless things, such as playing games all day or watching too much TV. When they grow old, they will regret it. We should make good use of our time. We should study hard, read books, and learn new skills. Every minute is precious. Remember, lost time is never found again. Let us cherish every moment and work hard for a better future.', storyZh: '时间是我们生命中最有价值的东西之一。它一旦流逝就永远不会回来。许多人把时间浪费在无用的事情上，比如整天玩游戏或看太多电视。当他们变老时会后悔的。我们应该好好利用时间。我们应该努力学习、读书、学习新技能。每一分钟都很珍贵。记住，丢失的时间再也找不回来。让我们珍惜每一刻，为更好的未来而努力。' },
        { en: 'The Power of Perseverance', zh: '坚持的力量', emoji: '💪', story: 'Perseverance is the key to success. Many great people in history achieved their goals because they never gave up. Thomas Edison failed thousands of times before he invented the light bulb. When others laughed at him, he said, "I have not failed. I have just found thousands of ways that do not work." His perseverance finally brought light to the world. In our daily life, we will meet many difficulties. Sometimes we may feel tired and want to give up. But if we keep trying, we will succeed in the end. Remember, nothing is impossible if you put your heart into it.', storyZh: '坚持是成功的关键。历史上许多伟人之所以能实现目标，是因为他们从不放弃。托马斯·爱迪生在发明电灯泡之前失败了数千次。当别人嘲笑他时，他说，我没有失败，我只是找到了数千种行不通的方法。他的坚持最终为世界带来了光明。在日常生活中，我们会遇到许多困难。有时我们会感到疲惫想放弃。但如果我们继续尝试，最终会成功的。记住，只要用心，没有什么是不可能的。' },
        { en: 'Protecting Our Environment', zh: '保护我们的环境', emoji: '🌍', story: 'Our planet is facing serious environmental problems. The air is polluted, the water is dirty, and many animals are losing their homes. We must do something to protect the environment. First, we can reduce waste by using less plastic and recycling more. Second, we can save energy by turning off lights when we leave a room and taking shorter showers. Third, we can plant more trees to make the air cleaner. Everyone can make a difference. Even small actions, like picking up litter or riding a bike instead of driving, can help. If we all work together, we can make the world a better place for future generations.', storyZh: '我们的星球正面临严重的环境问题。空气被污染，水变脏了，许多动物正在失去家园。我们必须做些什么来保护环境。首先，我们可以通过少用塑料和更多地回收来减少废物。其次，我们可以通过离开房间时关灯和缩短洗澡时间来节约能源。第三，我们可以种更多的树让空气更清新。每个人都能带来改变。即使是捡垃圾或骑自行车代替开车这样的小行动也能有所帮助。如果我们共同努力，就能为子孙后代让世界变得更美好。' },
        { en: 'The Joy of Reading', zh: '阅读的乐趣', emoji: '📚', story: 'Reading is a wonderful hobby that can bring us endless joy and knowledge. When we open a book, we enter a new world. We can travel to distant lands, meet interesting characters, and experience exciting adventures without leaving home. Books are also great teachers. They teach us about history, science, and culture. They help us think more deeply and understand the world better. Many successful people are avid readers. They read every day because they know that learning never stops. If you want to grow wiser and happier, develop the habit of reading. Start with books that interest you, and gradually explore different kinds of books. You will find that reading is one of the best things in life.', storyZh: '阅读是一种奇妙的爱好，能给我们带来无尽的快乐和知识。当我们打开一本书时，就进入了一个新世界。我们可以去遥远的地方，遇见有趣的人物，经历激动人心的冒险，而不用离开家。书也是伟大的老师。它们教我们历史、科学和文化。它们帮助我们更深入地思考，更好地理解世界。许多成功人士都是热心的读者。他们每天阅读，因为他们知道学习永无止境。如果你想变得更聪明更快乐，就养成阅读的习惯。从你感兴趣的书开始，逐渐探索不同类型的书。你会发现阅读是生活中最美好的事情之一。' },
        { en: 'Friendship', zh: '友谊', emoji: '🤝', story: 'Friendship is one of the most precious gifts in our lives. A true friend is someone who stays by your side when you are in trouble. They share your happiness and sadness, and they never judge you. Good friends trust each other and are honest with each other. They help each other grow and become better people. Making friends is easy, but keeping a friendship takes effort. We need to be loyal, kind, and patient. We should listen to our friends and support them when they need help. Sometimes friends may have disagreements, but they can always talk and solve the problems together. A real friendship can last a lifetime. Treasure your friends, because they make your life richer and more meaningful.', storyZh: '友谊是我们生命中最珍贵的礼物之一。真正的朋友是在你遇到困难时留在你身边的人。他们分享你的快乐和悲伤，从不评判你。好朋友相互信任，相互坦诚。他们帮助彼此成长，成为更好的人。交朋友很容易，但维持友谊需要努力。我们需要忠诚、善良和耐心。我们应该倾听朋友，在他们需要帮助时支持他们。有时朋友可能会有分歧，但他们总是可以交流并一起解决问题。真正的友谊可以持续一生。珍惜你的朋友，因为他们让你的生活更丰富、更有意义。' },
        { en: 'Dreams and Goals', zh: '梦想与目标', emoji: '🌟', story: 'Everyone has dreams. Some people want to be doctors, others want to be teachers or artists. Dreams give us direction and make our lives meaningful. However, a dream without action is just a wish. To make our dreams come true, we must set clear goals and work hard to achieve them. First, we should make a plan. Break a big dream into small, achievable steps. Second, we should take action every day. Even a small step forward brings us closer to our goal. Third, we should never give up. There will be difficulties and failures along the way, but they are part of the journey. Learn from your mistakes and keep moving. Remember, success belongs to those who never stop trying. Hold on to your dreams, and one day they will become reality.', storyZh: '每个人都有梦想。有些人想当医生，其他人想当老师或艺术家。梦想给我们方向，让我们的生活有意义。然而，没有行动的梦想只是愿望。要让梦想成真，我们必须设定明确的目标并努力实现它们。首先，我们应该制定计划。把大梦想分解成小的、可实现的步骤。其次，我们每天都应该采取行动。即使是向前的一小步也会让我们更接近目标。第三，我们永远不应该放弃。一路上会有困难和失败，但它们是旅程的一部分。从错误中学习并继续前进。记住，成功属于那些从不停止尝试的人。坚持你的梦想，总有一天它们会变成现实。' }
      ]
    }
  ];

  // 插入到 phrases 主题之前，使词汇主题集中
  const idx = THEMES.findIndex(function (t) { return t.id === 'phrases'; });
  if (idx >= 0) THEMES.splice(idx, 0, ...newThemes);
  else THEMES.push(...newThemes);

  // 注册到词汇题库池
  const newIds = newThemes.map(function (t) { return t.id; });
  if (typeof VOCAB_THEME_IDS !== 'undefined') newIds.forEach(function (id) { VOCAB_THEME_IDS.push(id); });
})();
